<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class KabupatenSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $kabupaten = [
            // WILAYAH I
            // aceh
            ['id' => 1, 'pj_id' => null, 'provinsi_id' => 1, 'nama' => 'Kab. Simeulue'],
            ['id' => 2, 'pj_id' => null, 'provinsi_id' => 1, 'nama' => 'Kab. Aceh Singkil'],
            ['id' => 3, 'pj_id' => null, 'provinsi_id' => 1, 'nama' => 'Kab. Aceh Selatan'],
            ['id' => 4, 'pj_id' => null, 'provinsi_id' => 1, 'nama' => 'Kab. Aceh Tenggara'],
            ['id' => 5, 'pj_id' => null, 'provinsi_id' => 1, 'nama' => 'Kab. Aceh Timur'],
            ['id' => 6, 'pj_id' => null, 'provinsi_id' => 1, 'nama' => 'Kab. Aceh Tengah'],
            ['id' => 7, 'pj_id' => null, 'provinsi_id' => 1, 'nama' => 'Kab. Aceh Barat'],
            ['id' => 8, 'pj_id' => null, 'provinsi_id' => 1, 'nama' => 'Kab. Aceh Besar'],
            ['id' => 9, 'pj_id' => null, 'provinsi_id' => 1, 'nama' => 'Kab. Pidie'],
            ['id' => 10, 'pj_id' => null, 'provinsi_id' => 1, 'nama' => 'Kab. Bireuen'],
            ['id' => 11, 'pj_id' => null, 'provinsi_id' => 1, 'nama' => 'Kab. Aceh Utara'],
            ['id' => 12, 'pj_id' => null, 'provinsi_id' => 1, 'nama' => 'Kab. Aceh Barat Daya'],
            ['id' => 13, 'pj_id' => null, 'provinsi_id' => 1, 'nama' => 'Kab. Gayo Lues'],
            ['id' => 14, 'pj_id' => null, 'provinsi_id' => 1, 'nama' => 'Kab. Aceh Tamiang'],
            ['id' => 15, 'pj_id' => null, 'provinsi_id' => 1, 'nama' => 'Kab. Nagan Raya'],
            ['id' => 16, 'pj_id' => null, 'provinsi_id' => 1, 'nama' => 'Kab. Aceh Jaya'],
            ['id' => 17, 'pj_id' => null, 'provinsi_id' => 1, 'nama' => 'Kab. Bener Meriah'],
            ['id' => 18, 'pj_id' => null, 'provinsi_id' => 1, 'nama' => 'Kab. Pidie Jaya'],
            ['id' => 19, 'pj_id' => null, 'provinsi_id' => 1, 'nama' => 'Kota Banda Aceh'],
            ['id' => 20, 'pj_id' => null, 'provinsi_id' => 1, 'nama' => 'Kota Sabang'],
            ['id' => 21, 'pj_id' => null, 'provinsi_id' => 1, 'nama' => 'Kota Langsa'],
            ['id' => 22, 'pj_id' => null, 'provinsi_id' => 1, 'nama' => 'Kota Lhokseumawe'],
            ['id' => 23, 'pj_id' => null, 'provinsi_id' => 1, 'nama' => 'Kota Subulussalam'],
            // sumut
            ['id' => 24, 'pj_id' => null, 'provinsi_id' => 2, 'nama' => 'Kab. Nias'],
            ['id' => 25, 'pj_id' => null, 'provinsi_id' => 2,'nama' => 'Kab. Mandailing Natal'],
            ['id' => 26, 'pj_id' => null, 'provinsi_id' => 2,'nama' => 'Kab. Tapanuli Selatan'],
            ['id' => 27, 'pj_id' => null, 'provinsi_id' => 2,'nama' => 'Kab. Tapanuli Tengah'],
            ['id' => 28, 'pj_id' => null, 'provinsi_id' => 2,'nama' => 'Kab. Tapanuli Utara'],
            ['id' => 29, 'pj_id' => null, 'provinsi_id' => 2,'nama' => 'Kab. Toba Samosir'],
            ['id' => 30, 'pj_id' => null, 'provinsi_id' => 2,'nama' => 'Kab. Labuhanbatu'],
            ['id' => 31, 'pj_id' => null, 'provinsi_id' => 2,'nama' => 'Kab. Asahan'],
            ['id' => 32, 'pj_id' => null, 'provinsi_id' => 2,'nama' => 'Kab. Simalungun'],
            ['id' => 33, 'pj_id' => null, 'provinsi_id' => 2,'nama' => 'Kab. Dairi'],
            ['id' => 34, 'pj_id' => null, 'provinsi_id' => 2,'nama' => 'Kab. Karo'],
            ['id' => 35, 'pj_id' => null, 'provinsi_id' => 2,'nama' => 'Kab. Deli Serdang'],
            ['id' => 36, 'pj_id' => null, 'provinsi_id' => 2,'nama' => 'Kab. Langkat'],
            ['id' => 37, 'pj_id' => null, 'provinsi_id' => 2,'nama' => 'Kab. Nias Selatan'],
            ['id' => 38, 'pj_id' => null, 'provinsi_id' => 2,'nama' => 'Kab. Humbang Hasundutan'],
            ['id' => 39, 'pj_id' => null, 'provinsi_id' => 2,'nama' => 'Kab. Pakpak Bharat'],
            ['id' => 40, 'pj_id' => null, 'provinsi_id' => 2,'nama' => 'Kab. Samosir'],
            ['id' => 41, 'pj_id' => null, 'provinsi_id' => 2,'nama' => 'Kab. Serdang Bedagai'],
            ['id' => 42, 'pj_id' => null, 'provinsi_id' => 2,'nama' => 'Kab. Batu Bara'],
            ['id' => 43, 'pj_id' => null, 'provinsi_id' => 2,'nama' => 'Kab. Padang Lawas Utara'],
            ['id' => 44, 'pj_id' => null, 'provinsi_id' => 2,'nama' => 'Kab. Padang Lawas'],
            ['id' => 45, 'pj_id' => null, 'provinsi_id' => 2,'nama' => 'Kab. Labuhanbatu Selatan'],
            ['id' => 46, 'pj_id' => null, 'provinsi_id' => 2,'nama' => 'Kab. Labuhanbatu Utara'],
            ['id' => 47, 'pj_id' => null, 'provinsi_id' => 2,'nama' => 'Kab. Nias Utara'],
            ['id' => 48, 'pj_id' => null, 'provinsi_id' => 2,'nama' => 'Kab. Nias Barat'],
            ['id' => 49, 'pj_id' => null, 'provinsi_id' => 2,'nama' => 'Kota ibolga'],
            ['id' => 50, 'pj_id' => null, 'provinsi_id' => 2,'nama' => 'Kota Tanjung Balai'],
            ['id' => 51, 'pj_id' => null, 'provinsi_id' => 2,'nama' => 'Kota Pematangsiantar'],
            ['id' => 52, 'pj_id' => null, 'provinsi_id' => 2,'nama' => 'Kota Tebing Tinggi'],
            ['id' => 53, 'pj_id' => null, 'provinsi_id' => 2,'nama' => 'Kota Medan'],
            ['id' => 54, 'pj_id' => null, 'provinsi_id' => 2,'nama' => 'Kota Binjai'],
            ['id' => 55, 'pj_id' => null, 'provinsi_id' => 2,'nama' => 'Kota Padang Sidempuan'],
            ['id' => 56, 'pj_id' => null, 'provinsi_id' => 2,'nama' => 'Kota Gunungsitoli'],
            // sumbar
            ['id' => 57, 'pj_id' => null, 'provinsi_id' => 3,'nama' => 'Kab. Kepulauan Mentawai'],
            ['id' => 58, 'pj_id' => null, 'provinsi_id' => 3, 'nama' => 'Kab. Pesisir Selatan'],
            ['id' => 59, 'pj_id' => null, 'provinsi_id' => 3, 'nama' => 'Kab. Solok'],
            ['id' => 60, 'pj_id' => null, 'provinsi_id' => 3, 'nama' => 'Kab. Sijunjung'],
            ['id' => 61, 'pj_id' => null, 'provinsi_id' => 3, 'nama' => 'Kab. Tanah Datar'],
            ['id' => 62, 'pj_id' => null, 'provinsi_id' => 3, 'nama' => 'Kab. Padang Pariaman'],
            ['id' => 63, 'pj_id' => null, 'provinsi_id' => 3, 'nama' => 'Kab. Agam'],
            ['id' => 64, 'pj_id' => null, 'provinsi_id' => 3, 'nama' => 'Kab. Lima Puluh Kota'],
            ['id' => 65, 'pj_id' => null, 'provinsi_id' => 3, 'nama' => 'Kab. Pasaman'],
            ['id' => 66, 'pj_id' => null, 'provinsi_id' => 3, 'nama' => 'Kab. Solok Selatan'],
            ['id' => 67, 'pj_id' => null, 'provinsi_id' => 3, 'nama' => 'Kab. Dharmasraya'],
            ['id' => 68, 'pj_id' => null, 'provinsi_id' => 3, 'nama' => 'Kab. Pasaman Barat'],
            ['id' => 69, 'pj_id' => null, 'provinsi_id' => 3, 'nama' => 'Kota Padang'],
            ['id' => 70, 'pj_id' => null, 'provinsi_id' => 3, 'nama' => 'Kota Solok'],
            ['id' => 71, 'pj_id' => null, 'provinsi_id' => 3, 'nama' => 'Kota Sawahlunto'],
            ['id' => 72, 'pj_id' => null, 'provinsi_id' => 3, 'nama' => 'Kota Padang Panjang'],
            ['id' => 73, 'pj_id' => null, 'provinsi_id' => 3, 'nama' => 'Kota Bukittinggi'],
            ['id' => 74, 'pj_id' => null, 'provinsi_id' => 3, 'nama' => 'Kota Payakumbuh'],
            ['id' => 75, 'pj_id' => null, 'provinsi_id' => 3, 'nama' => 'Kota Pariaman'],
            // riau
            ['id' => 76, 'pj_id' => null, 'provinsi_id' => 4, 'nama' => 'Kab. Kuantan Singingi'],
            ['id' => 77, 'pj_id' => null, 'provinsi_id' => 4, 'nama' => 'Kab. Indragiri Hulu'],
            ['id' => 78, 'pj_id' => null, 'provinsi_id' => 4, 'nama' => 'Kab. Indragiri Hilir'],
            ['id' => 79, 'pj_id' => null, 'provinsi_id' => 4, 'nama' => 'Kab. Pelalawan'],
            ['id' => 80, 'pj_id' => null, 'provinsi_id' => 4, 'nama' => 'Kab. Siak'],
            ['id' => 81, 'pj_id' => null, 'provinsi_id' => 4, 'nama' => 'Kab. Kampar'],
            ['id' => 82, 'pj_id' => null, 'provinsi_id' => 4, 'nama' => 'Kab. Rokan Hulu'],
            ['id' => 83, 'pj_id' => null, 'provinsi_id' => 4, 'nama' => 'Kab. Bengkalis'],
            ['id' => 84, 'pj_id' => null, 'provinsi_id' => 4, 'nama' => 'Kab. Rokan Hilir'],
            ['id' => 85, 'pj_id' => null, 'provinsi_id' => 4, 'nama' => 'Kab. Kepulauan Meranti'],
            ['id' => 86, 'pj_id' => null, 'provinsi_id' => 4, 'nama' => 'Kota Pekanbaru'],
            ['id' => 87, 'pj_id' => null, 'provinsi_id' => 4, 'nama' => 'Kota Dumai'],
            // jambi
            ['id' => 88, 'pj_id' => null, 'provinsi_id' => 5, 'nama' => 'Kab. Kerinci'],
            ['id' => 89, 'pj_id' => null, 'provinsi_id' => 5, 'nama' => 'Kab. Merangin'],
            ['id' => 90, 'pj_id' => null, 'provinsi_id' => 5, 'nama' => 'Kab. Sarolangun'],
            ['id' => 91, 'pj_id' => null, 'provinsi_id' => 5, 'nama' => 'Kab. Batanghari'],
            ['id' => 92, 'pj_id' => null, 'provinsi_id' => 5, 'nama' => 'Kab. Muaro Jambi'],
            ['id' => 93, 'pj_id' => null, 'provinsi_id' => 5, 'nama' => 'Kab. Tanjung Jabung Timur'],
            ['id' => 94, 'pj_id' => null, 'provinsi_id' => 5, 'nama' => 'Kab. Tanjung Jabung Barat'],
            ['id' => 95, 'pj_id' => null, 'provinsi_id' => 5, 'nama' => 'Kab. Tebo'],
            ['id' => 96, 'pj_id' => null, 'provinsi_id' => 5, 'nama' => 'Kab. Bungo'],
            ['id' => 97, 'pj_id' => null, 'provinsi_id' => 5, 'nama' => 'Kota Jambi'],
            ['id' => 98, 'pj_id' => null, 'provinsi_id' => 5, 'nama' => 'Kota Sungai Penuh'],
            // sumsel
            ['id' => 99, 'pj_id' => null, 'provinsi_id' => 6, 'nama' => 'Kab. Ogan Komering Ulu'],
            ['id' => 100, 'pj_id' => null, 'provinsi_id' => 6, 'nama' => 'Kab. Ogan Komering Ilir'],
            ['id' => 101, 'pj_id' => null, 'provinsi_id' => 6, 'nama' => 'Kab. Muara Enim'],
            ['id' => 102, 'pj_id' => null, 'provinsi_id' => 6, 'nama' => 'Kab. Lahat'],
            ['id' => 103, 'pj_id' => null, 'provinsi_id' => 6, 'nama' => 'Kab. Musi Rawas'],
            ['id' => 104, 'pj_id' => null, 'provinsi_id' => 6, 'nama' => 'Kab. Musi Banyuasin'],
            ['id' => 105, 'pj_id' => null, 'provinsi_id' => 6, 'nama' => 'Kab. Banyuasin'],
            ['id' => 106, 'pj_id' => null, 'provinsi_id' => 6, 'nama' => 'Kab. Ogan Komering Ulu Timur'],
            ['id' => 107, 'pj_id' => null, 'provinsi_id' => 6, 'nama' => 'Kab. Ogan Komering Ulu Selatan'],
            ['id' => 108, 'pj_id' => null, 'provinsi_id' => 6, 'nama' => 'Kab. Ogan Ilir'],
            ['id' => 109, 'pj_id' => null, 'provinsi_id' => 6, 'nama' => 'Kab. Empat Lawang'],
            ['id' => 110, 'pj_id' => null, 'provinsi_id' => 6, 'nama' => 'Kab. Penukal Abab Lematang'],
            ['id' => 111, 'pj_id' => null, 'provinsi_id' => 6, 'nama' => 'Kab. Musi Rawas Utara'],
            ['id' => 112, 'pj_id' => null, 'provinsi_id' => 6, 'nama' => 'Kota Palembang'],
            ['id' => 113, 'pj_id' => null, 'provinsi_id' => 6, 'nama' => 'Kota Prabumulih'],
            ['id' => 114, 'pj_id' => null, 'provinsi_id' => 6, 'nama' => 'Kota Pagar Alam'],
            ['id' => 115, 'pj_id' => null, 'provinsi_id' => 6, 'nama' => 'Kota Lubuk Linggau'],
            // bengkulu
            ['id' => 116, 'pj_id' => null, 'provinsi_id' => 7, 'nama' => 'Kab. Bengkulu Selatan'],
            ['id' => 117, 'pj_id' => null, 'provinsi_id' => 7, 'nama' => 'Kab. Rejang Lebong'],
            ['id' => 118, 'pj_id' => null, 'provinsi_id' => 7, 'nama' => 'Kab. Bengkulu Utara'],
            ['id' => 119, 'pj_id' => null, 'provinsi_id' => 7, 'nama' => 'Kab. Kaur'],
            ['id' => 120, 'pj_id' => null, 'provinsi_id' => 7, 'nama' => 'Kab. Seluma'],
            ['id' => 121, 'pj_id' => null, 'provinsi_id' => 7, 'nama' => 'Kab. Muko Muko'],
            ['id' => 122, 'pj_id' => null, 'provinsi_id' => 7, 'nama' => 'Kab. Lebong'],
            ['id' => 123, 'pj_id' => null, 'provinsi_id' => 7, 'nama' => 'Kab. Kepahiang'],
            ['id' => 124, 'pj_id' => null, 'provinsi_id' => 7, 'nama' => 'Kab. Bengkulu Tengah'],
            ['id' => 125, 'pj_id' => null, 'provinsi_id' => 7, 'nama' => 'Kota Bengkulu'],
            // babel
            ['id' => 126, 'pj_id' => null, 'provinsi_id' => 8, 'nama' => 'Kab. Bangka'],
            ['id' => 127, 'pj_id' => null, 'provinsi_id' => 8, 'nama' => 'Kab. Belitung'],
            ['id' => 128, 'pj_id' => null, 'provinsi_id' => 8, 'nama' => 'Kab. Bangka Barat'],
            ['id' => 129, 'pj_id' => null, 'provinsi_id' => 8, 'nama' => 'Kab. Bangka Tengah'],
            ['id' => 130, 'pj_id' => null, 'provinsi_id' => 8, 'nama' => 'Kab. Bangka Selatan'],
            ['id' => 131, 'pj_id' => null, 'provinsi_id' => 8, 'nama' => 'Kab. Belitung Timur'],
            ['id' => 132, 'pj_id' => null, 'provinsi_id' => 8, 'nama' => 'Kota Pangkal Pinang'],
            // lampung
            ['id' => 133, 'pj_id' => null, 'provinsi_id' => 9, 'nama' => 'Kab. Lampung Barat'],
            ['id' => 134, 'pj_id' => null, 'provinsi_id' => 9, 'nama' => 'Kab. Tanggamus'],
            ['id' => 135, 'pj_id' => null, 'provinsi_id' => 9, 'nama' => 'Kab. Lampung Selatan'],
            ['id' => 136, 'pj_id' => null, 'provinsi_id' => 9, 'nama' => 'Kab. Lampung Timur'],
            ['id' => 137, 'pj_id' => null, 'provinsi_id' => 9, 'nama' => 'Kab. Lampung Tengah'],
            ['id' => 138, 'pj_id' => null, 'provinsi_id' => 9, 'nama' => 'Kab. Lampung Utara'],
            ['id' => 139, 'pj_id' => null, 'provinsi_id' => 9, 'nama' => 'Kab. Way Kanan'],
            ['id' => 140, 'pj_id' => null, 'provinsi_id' => 9, 'nama' => 'Kab. Tulang Bawang'],
            ['id' => 141, 'pj_id' => null, 'provinsi_id' => 9, 'nama' => 'Kab. Pesawaran'],
            ['id' => 142, 'pj_id' => null, 'provinsi_id' => 9, 'nama' => 'Kab. Pringsewu'],
            ['id' => 143, 'pj_id' => null, 'provinsi_id' => 9, 'nama' => 'Kab. Mesuji'],
            ['id' => 144, 'pj_id' => null, 'provinsi_id' => 9, 'nama' => 'Kab. Tulang Bawang Barat'],
            ['id' => 145, 'pj_id' => null, 'provinsi_id' => 9, 'nama' => 'Kab. Pesisir Barat'],
            ['id' => 146, 'pj_id' => null, 'provinsi_id' => 9, 'nama' => 'Kota Bandar Lampung'],
            ['id' => 147, 'pj_id' => null, 'provinsi_id' => 9, 'nama' => 'Kota Metro'],
            
            // WILAYAH II
            // banten
            ['id' => 148, 'pj_id' => null, 'provinsi_id' => 10, 'nama' => 'Kab. Pandeglang'],
            ['id' => 149, 'pj_id' => null, 'provinsi_id' => 10, 'nama' => 'Kab. Lebak'],
            ['id' => 150, 'pj_id' => null, 'provinsi_id' => 10, 'nama' => 'Kab. Tangerang'],
            ['id' => 151, 'pj_id' => null, 'provinsi_id' => 10, 'nama' => 'Kab. Serang'],
            ['id' => 152, 'pj_id' => null, 'provinsi_id' => 10, 'nama' => 'Kota Tangerang'],
            ['id' => 153, 'pj_id' => null, 'provinsi_id' => 10, 'nama' => 'Kota Cilegon'],
            ['id' => 154, 'pj_id' => null, 'provinsi_id' => 10, 'nama' => 'Kota Serang'],
            ['id' => 155, 'pj_id' => null, 'provinsi_id' => 10, 'nama' => 'Kota Tangerang Selatan'],
            // jabar
            ['id' => 156, 'pj_id' => null, 'provinsi_id' => 11, 'nama' => 'Kab. Bogor'],
            ['id' => 157, 'pj_id' => null, 'provinsi_id' => 11, 'nama' => 'Kab. Sukabumi'],
            ['id' => 158, 'pj_id' => null, 'provinsi_id' => 11, 'nama' => 'Kab. Cianjur'],
            ['id' => 159, 'pj_id' => null, 'provinsi_id' => 11, 'nama' => 'Kab. Bandung'],
            ['id' => 160, 'pj_id' => null, 'provinsi_id' => 11, 'nama' => 'Kab. Garut'],
            ['id' => 161, 'pj_id' => null, 'provinsi_id' => 11, 'nama' => 'Kab. Tasikmalaya'],
            ['id' => 162, 'pj_id' => null, 'provinsi_id' => 11, 'nama' => 'Kab. Ciamis'],
            ['id' => 163, 'pj_id' => null, 'provinsi_id' => 11, 'nama' => 'Kab. Kuningan'],
            ['id' => 164, 'pj_id' => null, 'provinsi_id' => 11, 'nama' => 'Kab. Cirebon'],
            ['id' => 165, 'pj_id' => null, 'provinsi_id' => 11, 'nama' => 'Kab. Majalengka'],
            ['id' => 166, 'pj_id' => null, 'provinsi_id' => 11, 'nama' => 'Kab. Sumedang'],
            ['id' => 167, 'pj_id' => null, 'provinsi_id' => 11, 'nama' => 'Kab. Indramayu'],
            ['id' => 168, 'pj_id' => null, 'provinsi_id' => 11, 'nama' => 'Kab. Subang'],
            ['id' => 169, 'pj_id' => null, 'provinsi_id' => 11, 'nama' => 'Kab. Purwakarta'],
            ['id' => 170, 'pj_id' => null, 'provinsi_id' => 11, 'nama' => 'Kab. Karawang'],
            ['id' => 171, 'pj_id' => null, 'provinsi_id' => 11, 'nama' => 'Kab. Bekasi'],
            ['id' => 172, 'pj_id' => null, 'provinsi_id' => 11, 'nama' => 'Kab. Bandung Barat'],
            ['id' => 173, 'pj_id' => null, 'provinsi_id' => 11, 'nama' => 'Kab. Pangandaran'],
            ['id' => 174, 'pj_id' => null, 'provinsi_id' => 11, 'nama' => 'Kota Bogor'],
            ['id' => 175, 'pj_id' => null, 'provinsi_id' => 11, 'nama' => 'Kota Sukabumi'],
            ['id' => 176, 'pj_id' => null, 'provinsi_id' => 11, 'nama' => 'Kota Bandung'],
            ['id' => 177, 'pj_id' => null, 'provinsi_id' => 11, 'nama' => 'Kota Cirebon'],
            ['id' => 178, 'pj_id' => null, 'provinsi_id' => 11, 'nama' => 'Kota Bekasi'],
            ['id' => 179, 'pj_id' => null, 'provinsi_id' => 11, 'nama' => 'Kota Depok'],
            ['id' => 180, 'pj_id' => null, 'provinsi_id' => 11, 'nama' => 'Kota Cimahi'],
            ['id' => 181, 'pj_id' => null, 'provinsi_id' => 11, 'nama' => 'Kota Tasikmalaya'],
            ['id' => 182, 'pj_id' => null, 'provinsi_id' => 11, 'nama' => 'Kota Banjar'],
            // yogyakarta
            ['id' => 183, 'pj_id' => null, 'provinsi_id' => 12, 'nama' => 'Kab. Kulon Progo'],
            ['id' => 184, 'pj_id' => null, 'provinsi_id' => 12, 'nama' => 'Kab. Bantul'],
            ['id' => 185, 'pj_id' => null, 'provinsi_id' => 12, 'nama' => 'Kab. Gunungkidul'],
            ['id' => 186, 'pj_id' => null, 'provinsi_id' => 12, 'nama' => 'Kab. Sleman'],
            ['id' => 187, 'pj_id' => null, 'provinsi_id' => 12, 'nama' => 'Kota Yogyakarta'],
            // jateng
            ['id' => 189, 'pj_id' => null, 'provinsi_id' => 13, 'nama' => 'Cilacap'],
            ['id' => 190, 'pj_id' => null, 'provinsi_id' => 13, 'nama' => 'Banyumas'],
            ['id' => 191, 'pj_id' => null, 'provinsi_id' => 13, 'nama' => 'Purbalingga'],
            ['id' => 192, 'pj_id' => null, 'provinsi_id' => 13, 'nama' => 'Banjarnegara'],
            ['id' => 193, 'pj_id' => null, 'provinsi_id' => 13, 'nama' => 'Kebumen'],
            ['id' => 194, 'pj_id' => null, 'provinsi_id' => 13, 'nama' => 'Purworejo'],
            ['id' => 195, 'pj_id' => null, 'provinsi_id' => 13, 'nama' => 'Wonosobo'],
            ['id' => 196, 'pj_id' => null, 'provinsi_id' => 13, 'nama' => 'Magelang'],
            ['id' => 197, 'pj_id' => null, 'provinsi_id' => 13, 'nama' => 'Boyolali'],
            ['id' => 198, 'pj_id' => null, 'provinsi_id' => 13, 'nama' => 'Klaten'],
            ['id' => 199, 'pj_id' => null, 'provinsi_id' => 13, 'nama' => 'Sukoharjo'],
            ['id' => 200, 'pj_id' => null, 'provinsi_id' => 13, 'nama' => 'Wonogiri'],
            ['id' => 201, 'pj_id' => null, 'provinsi_id' => 13, 'nama' => 'Karanganyar'],
            ['id' => 202, 'pj_id' => null, 'provinsi_id' => 13, 'nama' => 'Sragen'],
            ['id' => 203, 'pj_id' => null, 'provinsi_id' => 13, 'nama' => 'Grobogan'],
            ['id' => 204, 'pj_id' => null, 'provinsi_id' => 13, 'nama' => 'Blora'],
            ['id' => 205, 'pj_id' => null, 'provinsi_id' => 13, 'nama' => 'Rembang'],
            ['id' => 206, 'pj_id' => null, 'provinsi_id' => 13, 'nama' => 'Pati'],
            ['id' => 207, 'pj_id' => null, 'provinsi_id' => 13, 'nama' => 'Kudus'],
            ['id' => 208, 'pj_id' => null, 'provinsi_id' => 13, 'nama' => 'Jepara'],
            ['id' => 209, 'pj_id' => null, 'provinsi_id' => 13, 'nama' => 'Demak'],
            ['id' => 210, 'pj_id' => null, 'provinsi_id' => 13, 'nama' => 'Semarang'],
            ['id' => 211, 'pj_id' => null, 'provinsi_id' => 13, 'nama' => 'Temanggung'],
            ['id' => 212, 'pj_id' => null, 'provinsi_id' => 13, 'nama' => 'Kendal'],
            ['id' => 213, 'pj_id' => null, 'provinsi_id' => 13, 'nama' => 'Batang'],
            ['id' => 214, 'pj_id' => null, 'provinsi_id' => 13, 'nama' => 'Pekalongan'],
            ['id' => 215, 'pj_id' => null, 'provinsi_id' => 13, 'nama' => 'Pemalang'],
            ['id' => 216, 'pj_id' => null, 'provinsi_id' => 13, 'nama' => 'Tegal'],
            ['id' => 217, 'pj_id' => null, 'provinsi_id' => 13, 'nama' => 'Brebes'],
            ['id' => 218, 'pj_id' => null, 'provinsi_id' => 13, 'nama' => 'Magelang'],
            ['id' => 219, 'pj_id' => null, 'provinsi_id' => 13, 'nama' => 'Surakarta'],
            ['id' => 220, 'pj_id' => null, 'provinsi_id' => 13, 'nama' => 'Salatiga'],
            ['id' => 221, 'pj_id' => null, 'provinsi_id' => 13, 'nama' => 'Semarang'],
            ['id' => 222, 'pj_id' => null, 'provinsi_id' => 13, 'nama' => 'Pekalongan'],
            ['id' => 223, 'pj_id' => null, 'provinsi_id' => 13, 'nama' => 'Tegal'],
            // jatim
            ['id' => 224, 'pj_id' => null, 'provinsi_id' => 14, 'nama' => 'Kab. Pacitan'],
            ['id' => 225, 'pj_id' => null, 'provinsi_id' => 14, 'nama' => 'Kab. Ponorogo'],
            ['id' => 226, 'pj_id' => null, 'provinsi_id' => 14, 'nama' => 'Kab. Trenggalek'],
            ['id' => 227, 'pj_id' => null, 'provinsi_id' => 14, 'nama' => 'Kab. Tulungagung'],
            ['id' => 228, 'pj_id' => null, 'provinsi_id' => 14, 'nama' => 'Kab. Blitar'],
            ['id' => 229, 'pj_id' => null, 'provinsi_id' => 14, 'nama' => 'Kab. Kediri'],
            ['id' => 230, 'pj_id' => null, 'provinsi_id' => 14, 'nama' => 'Kab. Malang'],
            ['id' => 231, 'pj_id' => null, 'provinsi_id' => 14, 'nama' => 'Kab. Lumajang'],
            ['id' => 232, 'pj_id' => null, 'provinsi_id' => 14, 'nama' => 'Kab. Jember'],
            ['id' => 233, 'pj_id' => null, 'provinsi_id' => 14, 'nama' => 'Kab. Banyuwangi'],
            ['id' => 234, 'pj_id' => null, 'provinsi_id' => 14, 'nama' => 'Kab. Bondowoso'],
            ['id' => 235, 'pj_id' => null, 'provinsi_id' => 14, 'nama' => 'Kab. Situbondo'],
            ['id' => 236, 'pj_id' => null, 'provinsi_id' => 14, 'nama' => 'Kab. Probolinggo'],
            ['id' => 237, 'pj_id' => null, 'provinsi_id' => 14, 'nama' => 'Kab. Pasuruan'],
            ['id' => 238, 'pj_id' => null, 'provinsi_id' => 14, 'nama' => 'Kab. Sidoarjo'],
            ['id' => 239, 'pj_id' => null, 'provinsi_id' => 14, 'nama' => 'Kab. Mojokerto'],
            ['id' => 240, 'pj_id' => null, 'provinsi_id' => 14, 'nama' => 'Kab. Jombang'],
            ['id' => 241, 'pj_id' => null, 'provinsi_id' => 14, 'nama' => 'Kab. Nganjuk'],
            ['id' => 242, 'pj_id' => null, 'provinsi_id' => 14, 'nama' => 'Kab. Madiun'],
            ['id' => 243, 'pj_id' => null, 'provinsi_id' => 14, 'nama' => 'Kab. Magetan'],
            ['id' => 244, 'pj_id' => null, 'provinsi_id' => 14, 'nama' => 'Kab. Ngawi'],
            ['id' => 245, 'pj_id' => null, 'provinsi_id' => 14, 'nama' => 'Kab. Bojonegoro'],
            ['id' => 246, 'pj_id' => null, 'provinsi_id' => 14, 'nama' => 'Kab. Tuban'],
            ['id' => 247, 'pj_id' => null, 'provinsi_id' => 14, 'nama' => 'Kab. Lamongan'],
            ['id' => 248, 'pj_id' => null, 'provinsi_id' => 14, 'nama' => 'Kab. Gresik'],
            ['id' => 249, 'pj_id' => null, 'provinsi_id' => 14, 'nama' => 'Kab. Bangkalan'],
            ['id' => 250, 'pj_id' => null, 'provinsi_id' => 14, 'nama' => 'Kab. Sampang'],
            ['id' => 251, 'pj_id' => null, 'provinsi_id' => 14, 'nama' => 'Kab. Pamekasan'],
            ['id' => 252, 'pj_id' => null, 'provinsi_id' => 14, 'nama' => 'Kab. Sumenep'],
            ['id' => 253, 'pj_id' => null, 'provinsi_id' => 14, 'nama' => 'Kota Kediri'],
            ['id' => 254, 'pj_id' => null, 'provinsi_id' => 14, 'nama' => 'Kota Blitar'],
            ['id' => 255, 'pj_id' => null, 'provinsi_id' => 14, 'nama' => 'Kota Malang'],
            ['id' => 256, 'pj_id' => null, 'provinsi_id' => 14, 'nama' => 'Kota Probolinggo'],
            ['id' => 257, 'pj_id' => null, 'provinsi_id' => 14, 'nama' => 'Kota Pasuruan'],
            ['id' => 258, 'pj_id' => null, 'provinsi_id' => 14, 'nama' => 'Kota Mojokerto'],
            ['id' => 259, 'pj_id' => null, 'provinsi_id' => 14, 'nama' => 'Kota Madiun'],
            ['id' => 260, 'pj_id' => null, 'provinsi_id' => 14, 'nama' => 'Kota Surabaya'],
            ['id' => 261, 'pj_id' => null, 'provinsi_id' => 14, 'nama' => 'Kota Batu'],
            
            // WILAYAH III
            // bali
            ['id' => 262, 'pj_id' => null, 'provinsi_id' => 15, 'nama' => 'Kab. Jembrana'],
            ['id' => 263, 'pj_id' => null, 'provinsi_id' => 15, 'nama' => 'Kab. Tabanan'],
            ['id' => 264, 'pj_id' => null, 'provinsi_id' => 15, 'nama' => 'Kab. Badung'],
            ['id' => 265, 'pj_id' => null, 'provinsi_id' => 15, 'nama' => 'Kab. Gianyar'],
            ['id' => 266, 'pj_id' => null, 'provinsi_id' => 15, 'nama' => 'Kab. Klungkung'],
            ['id' => 267, 'pj_id' => null, 'provinsi_id' => 15, 'nama' => 'Kab. Bangli'],
            ['id' => 268, 'pj_id' => null, 'provinsi_id' => 15, 'nama' => 'Kab. Karangasem'],
            ['id' => 269, 'pj_id' => null, 'provinsi_id' => 15, 'nama' => 'Kab. Buleleng'],
            ['id' => 270, 'pj_id' => null, 'provinsi_id' => 15, 'nama' => 'Kota Denpasar'],
            // ntb
            ['id' => 271, 'pj_id' => null, 'provinsi_id' => 16, 'nama' => 'Kab. Lombok Barat'],
            ['id' => 272, 'pj_id' => null, 'provinsi_id' => 16, 'nama' => 'Kab. Lombok Tengah'],
            ['id' => 273, 'pj_id' => null, 'provinsi_id' => 16, 'nama' => 'Kab. Lombok Timur'],
            ['id' => 274, 'pj_id' => null, 'provinsi_id' => 16, 'nama' => 'Kab. Sumbawa'],
            ['id' => 275, 'pj_id' => null, 'provinsi_id' => 16, 'nama' => 'Kab. Dompu'],
            ['id' => 276, 'pj_id' => null, 'provinsi_id' => 16, 'nama' => 'Kab. Bima'],
            ['id' => 277, 'pj_id' => null, 'provinsi_id' => 16, 'nama' => 'Kab. Sumbawa Barat'],
            ['id' => 278, 'pj_id' => null, 'provinsi_id' => 16, 'nama' => 'Kab. Lombok Utara'],
            ['id' => 279, 'pj_id' => null, 'provinsi_id' => 16, 'nama' => 'Kota Mataram'],
            ['id' => 280, 'pj_id' => null, 'provinsi_id' => 16, 'nama' => 'Kota Bima'],
            // kalsel
            ['id' => 281, 'pj_id' => null, 'provinsi_id' => 17, 'nama' => 'Kab. Tanah Laut'],
            ['id' => 282, 'pj_id' => null, 'provinsi_id' => 17, 'nama' => 'Kab. Kotabaru'],
            ['id' => 283, 'pj_id' => null, 'provinsi_id' => 17, 'nama' => 'Kab. Banjar'],
            ['id' => 284, 'pj_id' => null, 'provinsi_id' => 17, 'nama' => 'Kab. Barito Kuala'],
            ['id' => 285, 'pj_id' => null, 'provinsi_id' => 17, 'nama' => 'Kab. Tapin'],
            ['id' => 286, 'pj_id' => null, 'provinsi_id' => 17, 'nama' => 'Kab. Hulu Sungai Selatan'],
            ['id' => 287, 'pj_id' => null, 'provinsi_id' => 17, 'nama' => 'Kab. Hulu Sungai Tengah'],
            ['id' => 288, 'pj_id' => null, 'provinsi_id' => 17, 'nama' => 'Kab. Hulu Sungai Utara'],
            ['id' => 289, 'pj_id' => null, 'provinsi_id' => 17, 'nama' => 'Kab. Tabalong'],
            ['id' => 290, 'pj_id' => null, 'provinsi_id' => 17, 'nama' => 'Kab. Tanah Bumbu'],
            ['id' => 291, 'pj_id' => null, 'provinsi_id' => 17, 'nama' => 'Kab. Balangan'],
            ['id' => 292, 'pj_id' => null, 'provinsi_id' => 17, 'nama' => 'Kota Banjarmasin'],
            ['id' => 293, 'pj_id' => null, 'provinsi_id' => 17, 'nama' => 'Kota Banjarbaru'],
            // kalbar
            ['id' => 294, 'pj_id' => null, 'provinsi_id' => 18, 'nama' => 'Kab. Tanah Laut'],
            ['id' => 295, 'pj_id' => null, 'provinsi_id' => 18, 'nama' => 'Kab. Kotabaru'],
            ['id' => 296, 'pj_id' => null, 'provinsi_id' => 18, 'nama' => 'Kab. Banjar'],
            ['id' => 297, 'pj_id' => null, 'provinsi_id' => 18, 'nama' => 'Kab. Barito Kuala'],
            ['id' => 298, 'pj_id' => null, 'provinsi_id' => 18, 'nama' => 'Kab. Tapin'],
            ['id' => 299, 'pj_id' => null, 'provinsi_id' => 18, 'nama' => 'Kab. Hulu Sungai Selatan'],
            ['id' => 300, 'pj_id' => null, 'provinsi_id' => 18, 'nama' => 'Kab. Hulu Sungai Tengah'],
            ['id' => 301, 'pj_id' => null, 'provinsi_id' => 18, 'nama' => 'Kab. Hulu Sungai Utara'],
            ['id' => 302, 'pj_id' => null, 'provinsi_id' => 18, 'nama' => 'Kab. Tabalong'],
            ['id' => 303, 'pj_id' => null, 'provinsi_id' => 18, 'nama' => 'Kab. Tanah Bumbu'],
            ['id' => 304, 'pj_id' => null, 'provinsi_id' => 18, 'nama' => 'Kab. Balangan'],
            ['id' => 305, 'pj_id' => null, 'provinsi_id' => 18, 'nama' => 'Kota Banjarmasin'],
            ['id' => 306, 'pj_id' => null, 'provinsi_id' => 18, 'nama' => 'Kota Banjarbaru'],
            // kalteng
            ['id' => 308, 'pj_id' => null, 'provinsi_id' => 19, 'nama' => 'Kab. Kotawaringin Barat'],
            ['id' => 309, 'pj_id' => null, 'provinsi_id' => 19, 'nama' => 'Kab. Kotawaringin Timur'],
            ['id' => 310, 'pj_id' => null, 'provinsi_id' => 19, 'nama' => 'Kab. Kapuas'],
            ['id' => 311, 'pj_id' => null, 'provinsi_id' => 19, 'nama' => 'Kab. Barito Selatan'],
            ['id' => 312, 'pj_id' => null, 'provinsi_id' => 19, 'nama' => 'Kab. Barito Utara'],
            ['id' => 313, 'pj_id' => null, 'provinsi_id' => 19, 'nama' => 'Kab. Sukamara'],
            ['id' => 314, 'pj_id' => null, 'provinsi_id' => 19, 'nama' => 'Kab. Lamandau'],
            ['id' => 315, 'pj_id' => null, 'provinsi_id' => 19, 'nama' => 'Kab. Seruyan'],
            ['id' => 316, 'pj_id' => null, 'provinsi_id' => 19, 'nama' => 'Kab. Katingan'],
            ['id' => 317, 'pj_id' => null, 'provinsi_id' => 19, 'nama' => 'Kab. Pulang Pisau'],
            ['id' => 318, 'pj_id' => null, 'provinsi_id' => 19, 'nama' => 'Kab. Gunung Mas'],
            ['id' => 319, 'pj_id' => null, 'provinsi_id' => 19, 'nama' => 'Kab. Barito Timur'],
            ['id' => 320, 'pj_id' => null, 'provinsi_id' => 19, 'nama' => 'Kab. Murung Raya'],
            ['id' => 321, 'pj_id' => null, 'provinsi_id' => 19, 'nama' => 'Kota Palangkaraya'],
            // kaltim
            ['id' => 322, 'pj_id' => null, 'provinsi_id' => 20, 'nama' => 'Kab. Paser'],
            ['id' => 323, 'pj_id' => null, 'provinsi_id' => 20, 'nama' => 'Kab. Kutai Barat'],
            ['id' => 324, 'pj_id' => null, 'provinsi_id' => 20, 'nama' => 'Kab. Kutai Kartanegara'],
            ['id' => 325, 'pj_id' => null, 'provinsi_id' => 20, 'nama' => 'Kab. Kutai Timur'],
            ['id' => 326, 'pj_id' => null, 'provinsi_id' => 20, 'nama' => 'Kab. Berau'],
            ['id' => 327, 'pj_id' => null, 'provinsi_id' => 20, 'nama' => 'Kab. Penajam Paser Utara'],
            ['id' => 328, 'pj_id' => null, 'provinsi_id' => 20, 'nama' => 'Kab. Mahakam Ulu'],
            ['id' => 329, 'pj_id' => null, 'provinsi_id' => 20, 'nama' => 'Kota Balikpapan'],
            ['id' => 330, 'pj_id' => null, 'provinsi_id' => 20, 'nama' => 'Kota Samarinda'],
            ['id' => 331, 'pj_id' => null, 'provinsi_id' => 20, 'nama' => 'Kota Bontang'],
            // kaltara
            ['id' => 332, 'pj_id' => null, 'provinsi_id' => 21, 'nama' => 'Kab. Malinau'],
            ['id' => 333, 'pj_id' => null, 'provinsi_id' => 21, 'nama' => 'Kab. Bulungan'],
            ['id' => 334, 'pj_id' => null, 'provinsi_id' => 21, 'nama' => 'Kab. Tana Tidung'],
            ['id' => 335, 'pj_id' => null, 'provinsi_id' => 21, 'nama' => 'Kab. Nunukan'],
            ['id' => 336, 'pj_id' => null, 'provinsi_id' => 21, 'nama' => 'Kab. Tarakan'],
            
            // WILAYAH IV
            // ntt
            ['id' => 337, 'pj_id' => null, 'provinsi_id' => 22, 'nama' => 'Kab. Sumba Barat'],
            ['id' => 338, 'pj_id' => null, 'provinsi_id' => 22, 'nama' => 'Kab. Sumba Timur'],
            ['id' => 339, 'pj_id' => null, 'provinsi_id' => 22, 'nama' => 'Kab. Kupang'],
            ['id' => 340, 'pj_id' => null, 'provinsi_id' => 22, 'nama' => 'Kab Timor Tengah Selatan'],
            ['id' => 341, 'pj_id' => null, 'provinsi_id' => 22, 'nama' => 'Kab. Timor Tengah Utara'],
            ['id' => 342, 'pj_id' => null, 'provinsi_id' => 22, 'nama' => 'Kab. Belu'],
            ['id' => 343, 'pj_id' => null, 'provinsi_id' => 22, 'nama' => 'Kab. Alor'],
            ['id' => 344, 'pj_id' => null, 'provinsi_id' => 22, 'nama' => 'Kab. Lembata'],
            ['id' => 345, 'pj_id' => null, 'provinsi_id' => 22, 'nama' => 'Kab. Flores Timur'],
            ['id' => 346, 'pj_id' => null, 'provinsi_id' => 22, 'nama' => 'Kab. Sikka'],
            ['id' => 347, 'pj_id' => null, 'provinsi_id' => 22, 'nama' => 'Kab. Ende'],
            ['id' => 348, 'pj_id' => null, 'provinsi_id' => 22, 'nama' => 'Kab. Ngada'],
            ['id' => 349, 'pj_id' => null, 'provinsi_id' => 22, 'nama' => 'Kab. Manggarai'],
            ['id' => 350, 'pj_id' => null, 'provinsi_id' => 22, 'nama' => 'Kab. Rote Ndao'],
            ['id' => 351, 'pj_id' => null, 'provinsi_id' => 22, 'nama' => 'Kab. Manggarai Barat'],
            ['id' => 352, 'pj_id' => null, 'provinsi_id' => 22, 'nama' => 'Kab. Sumba Tengah'],
            ['id' => 353, 'pj_id' => null, 'provinsi_id' => 22, 'nama' => 'Kab. Sumba Barat Daya'],
            ['id' => 354, 'pj_id' => null, 'provinsi_id' => 22, 'nama' => 'Kab. Nagekeo'],
            ['id' => 355, 'pj_id' => null, 'provinsi_id' => 22, 'nama' => 'Kab. Manggarai Timur'],
            ['id' => 356, 'pj_id' => null, 'provinsi_id' => 22, 'nama' => 'Kab. Sabu Raijua'],
            ['id' => 357, 'pj_id' => null, 'provinsi_id' => 22, 'nama' => 'Kab. Malaka'],
            ['id' => 358, 'pj_id' => null, 'provinsi_id' => 22, 'nama' => 'Kota Kupang'],
            // sulut
            ['id' => 359, 'pj_id' => null, 'provinsi_id' => 23, 'nama' => 'Kab. Bolaang Mongondow Utara'],
            ['id' => 360, 'pj_id' => null, 'provinsi_id' => 23, 'nama' => 'Kab. Minahasa'],
            ['id' => 361, 'pj_id' => null, 'provinsi_id' => 23, 'nama' => 'Kab. Kepulauan Sangihe'],
            ['id' => 362, 'pj_id' => null, 'provinsi_id' => 23, 'nama' => 'Kab. Kepulauan Talaud'],
            ['id' => 363, 'pj_id' => null, 'provinsi_id' => 23, 'nama' => 'Kab. Minahasa Selatan'],
            ['id' => 364, 'pj_id' => null, 'provinsi_id' => 23, 'nama' => 'Kab. Minahasa Utara'],
            ['id' => 365, 'pj_id' => null, 'provinsi_id' => 23, 'nama' => 'Kab. Bolaang Mongondow Timur'],
            ['id' => 366, 'pj_id' => null, 'provinsi_id' => 23, 'nama' => 'Kab. Kep. Siau Tagulandang'],
            ['id' => 367, 'pj_id' => null, 'provinsi_id' => 23, 'nama' => 'Kab. Minahasa Tenggara'],
            ['id' => 368, 'pj_id' => null, 'provinsi_id' => 23, 'nama' => 'Kab. Bolaang Mongondow'],
            ['id' => 369, 'pj_id' => null, 'provinsi_id' => 23, 'nama' => 'Kab. Bolaang Mongondow Selatan'],
            ['id' => 370, 'pj_id' => null, 'provinsi_id' => 23, 'nama' => 'Kota Manado'],
            ['id' => 371, 'pj_id' => null, 'provinsi_id' => 23, 'nama' => 'Kota Bitung'],
            ['id' => 372, 'pj_id' => null, 'provinsi_id' => 23, 'nama' => 'Kota Tomohon'],
            ['id' => 373, 'pj_id' => null, 'provinsi_id' => 23, 'nama' => 'Kota Kotamobagu'],
            // sulbar
            ['id' => 374, 'pj_id' => null, 'provinsi_id' => 24, 'nama' => 'Kab. Majene'],
            ['id' => 375, 'pj_id' => null, 'provinsi_id' => 24, 'nama' => 'Kab. Polewali Mandar'],
            ['id' => 376, 'pj_id' => null, 'provinsi_id' => 24, 'nama' => 'Kab. Mamasa'],
            ['id' => 377, 'pj_id' => null, 'provinsi_id' => 24, 'nama' => 'Kab. Mamuju'],
            ['id' => 378, 'pj_id' => null, 'provinsi_id' => 24, 'nama' => 'Kab. Pasangkayu'],
            // sultra
            ['id' => 379, 'pj_id' => null, 'provinsi_id' => 25, 'nama' => 'Kab. Buton'],
            ['id' => 380, 'pj_id' => null, 'provinsi_id' => 25, 'nama' => 'Kab. Muna'],
            ['id' => 381, 'pj_id' => null, 'provinsi_id' => 25, 'nama' => 'Kab. Konawe'],
            ['id' => 382, 'pj_id' => null, 'provinsi_id' => 25, 'nama' => 'Kab. Kolaka'],
            ['id' => 383, 'pj_id' => null, 'provinsi_id' => 25, 'nama' => 'Kab. Konawe Selatan'],
            ['id' => 384, 'pj_id' => null, 'provinsi_id' => 25, 'nama' => 'Kab. Bombana'],
            ['id' => 385, 'pj_id' => null, 'provinsi_id' => 25, 'nama' => 'Kab. Wakatobi'],
            ['id' => 386, 'pj_id' => null, 'provinsi_id' => 25, 'nama' => 'Kab. Kolaka Utara'],
            ['id' => 387, 'pj_id' => null, 'provinsi_id' => 25, 'nama' => 'Kab. Buton Utara'],
            ['id' => 388, 'pj_id' => null, 'provinsi_id' => 25, 'nama' => 'Kab. Konawe Utara'],
            ['id' => 389, 'pj_id' => null, 'provinsi_id' => 25, 'nama' => 'Kab. Kolaka Timur'],
            ['id' => 390, 'pj_id' => null, 'provinsi_id' => 25, 'nama' => 'Kab. Konawe Kepulauan'],
            ['id' => 391, 'pj_id' => null, 'provinsi_id' => 25, 'nama' => 'Kab. Muna Barat'],
            ['id' => 392, 'pj_id' => null, 'provinsi_id' => 25, 'nama' => 'Kab. Buton Tengah'],
            ['id' => 393, 'pj_id' => null, 'provinsi_id' => 25, 'nama' => 'Kab. Buton Selatan'],
            ['id' => 394, 'pj_id' => null, 'provinsi_id' => 25, 'nama' => 'Kota Kendari'],
            ['id' => 395, 'pj_id' => null, 'provinsi_id' => 25, 'nama' => 'Kota Bau Bau'],
            // sulteng
            ['id' => 396, 'pj_id' => null, 'provinsi_id' => 26, 'nama' => 'Kab. Banggai Kepulauan'],
            ['id' => 397, 'pj_id' => null, 'provinsi_id' => 26, 'nama' => 'Kab. Banggai'],
            ['id' => 398, 'pj_id' => null, 'provinsi_id' => 26, 'nama' => 'Kab. Morowali'],
            ['id' => 399, 'pj_id' => null, 'provinsi_id' => 26, 'nama' => 'Kab. Poso'],
            ['id' => 401, 'pj_id' => null, 'provinsi_id' => 26, 'nama' => 'Kab. Donggala'],
            ['id' => 402, 'pj_id' => null, 'provinsi_id' => 26, 'nama' => 'Kab. Toli Toli'],
            ['id' => 403, 'pj_id' => null, 'provinsi_id' => 26, 'nama' => 'Kab. Buol'],
            ['id' => 404, 'pj_id' => null, 'provinsi_id' => 26, 'nama' => 'Kab. Parigi Moutong'],
            ['id' => 405, 'pj_id' => null, 'provinsi_id' => 26, 'nama' => 'Kab. Tojo Una Una'],
            ['id' => 406, 'pj_id' => null, 'provinsi_id' => 26, 'nama' => 'Kab. Sigi'],
            ['id' => 407, 'pj_id' => null, 'provinsi_id' => 26, 'nama' => 'Kab. Banggai Laut'],
            ['id' => 408, 'pj_id' => null, 'provinsi_id' => 26, 'nama' => 'Kab. Morowali Utara'],
            ['id' => 409, 'pj_id' => null, 'provinsi_id' => 26, 'nama' => 'Kota Palu'],
            // sulsel
            ['id' => 410, 'pj_id' => null, 'provinsi_id' => 27, 'nama' => 'Kab. Kepulauan Selayar'],
            ['id' => 411, 'pj_id' => null, 'provinsi_id' => 27, 'nama' => 'Kab. Bulukumba'],
            ['id' => 412, 'pj_id' => null, 'provinsi_id' => 27, 'nama' => 'Kab. Bantaeng'],
            ['id' => 413, 'pj_id' => null, 'provinsi_id' => 27, 'nama' => 'Kab. Jeneponto'],
            ['id' => 414, 'pj_id' => null, 'provinsi_id' => 27, 'nama' => 'Kab. Takalar'],
            ['id' => 415, 'pj_id' => null, 'provinsi_id' => 27, 'nama' => 'Kab. Gowa'],
            ['id' => 416, 'pj_id' => null, 'provinsi_id' => 27, 'nama' => 'Kab. Sinjai'],
            ['id' => 417, 'pj_id' => null, 'provinsi_id' => 27, 'nama' => 'Kab. Maros'],
            ['id' => 418, 'pj_id' => null, 'provinsi_id' => 27, 'nama' => 'Kab. Pangkajene Kepulauan'],
            ['id' => 419, 'pj_id' => null, 'provinsi_id' => 27, 'nama' => 'Kab. Barru'],
            ['id' => 420, 'pj_id' => null, 'provinsi_id' => 27, 'nama' => 'Kab. Bone'],
            ['id' => 421, 'pj_id' => null, 'provinsi_id' => 27, 'nama' => 'Kab. Soppeng'],
            ['id' => 422, 'pj_id' => null, 'provinsi_id' => 27, 'nama' => 'Kab. Wajo'],
            ['id' => 423, 'pj_id' => null, 'provinsi_id' => 27, 'nama' => 'Kab. Sidenreng Rappang'],
            ['id' => 424, 'pj_id' => null, 'provinsi_id' => 27, 'nama' => 'Kab. Pinrang'],
            ['id' => 425, 'pj_id' => null, 'provinsi_id' => 27, 'nama' => 'Kab. Enrekang'],
            ['id' => 426, 'pj_id' => null, 'provinsi_id' => 27, 'nama' => 'Kab. Luwu'],
            ['id' => 427, 'pj_id' => null, 'provinsi_id' => 27, 'nama' => 'Kab. Tana Toraja'],
            ['id' => 428, 'pj_id' => null, 'provinsi_id' => 27, 'nama' => 'Kab. Luwu Utara'],
            ['id' => 429, 'pj_id' => null, 'provinsi_id' => 27, 'nama' => 'Kab. Luwu Timur'],
            ['id' => 430, 'pj_id' => null, 'provinsi_id' => 27, 'nama' => 'Kab. Toraja Utara'],
            ['id' => 431, 'pj_id' => null, 'provinsi_id' => 27, 'nama' => 'Kota Makassar'],
            ['id' => 432, 'pj_id' => null, 'provinsi_id' => 27, 'nama' => 'Kota Pare Pare'],
            ['id' => 433, 'pj_id' => null, 'provinsi_id' => 27, 'nama' => 'Kota Palopo'],
            // gorontalo
            ['id' => 434, 'pj_id' => null, 'provinsi_id' => 28, 'nama' => 'Kab. Boalemo'],
            ['id' => 435, 'pj_id' => null, 'provinsi_id' => 28, 'nama' => 'Kab. Gorontalo'],
            ['id' => 436, 'pj_id' => null, 'provinsi_id' => 28, 'nama' => 'Kab. Pahuwato'],
            ['id' => 437, 'pj_id' => null, 'provinsi_id' => 28, 'nama' => 'Kab. Bone Bolango'],
            ['id' => 438, 'pj_id' => null, 'provinsi_id' => 28, 'nama' => 'Kab. Gorontalo Utara'],
            ['id' => 439, 'pj_id' => null, 'provinsi_id' => 28, 'nama' => 'Kota Gorontalo'],
            // maluku
            ['id' => 440, 'pj_id' => null, 'provinsi_id' => 29, 'nama' => 'Kab. Kepulauan Tanimbar'],
            ['id' => 441, 'pj_id' => null, 'provinsi_id' => 29, 'nama' => 'Kab. Maluku Tenggara'],
            ['id' => 442, 'pj_id' => null, 'provinsi_id' => 29, 'nama' => 'Kab. Maluku Tengah'],
            ['id' => 443, 'pj_id' => null, 'provinsi_id' => 29, 'nama' => 'Kab. Buru'],
            ['id' => 444, 'pj_id' => null, 'provinsi_id' => 29, 'nama' => 'Kab. Kepulauan Aru'],
            ['id' => 445, 'pj_id' => null, 'provinsi_id' => 29, 'nama' => 'Kab. Seram Bagian Barat'],
            ['id' => 446, 'pj_id' => null, 'provinsi_id' => 29, 'nama' => 'Kab. Seram Bagian Timur'],
            ['id' => 447, 'pj_id' => null, 'provinsi_id' => 29, 'nama' => 'Kab. Maluku Barat Daya'],
            ['id' => 448, 'pj_id' => null, 'provinsi_id' => 29, 'nama' => 'Kab. Buru Selatan'],
            ['id' => 449, 'pj_id' => null, 'provinsi_id' => 29, 'nama' => 'Kota Ambon'],
            ['id' => 450, 'pj_id' => null, 'provinsi_id' => 29, 'nama' => 'Kota Tual'],
            // malut
            ['id' => 451, 'pj_id' => null, 'provinsi_id' => 30, 'nama' => 'Kab. Halmahera Barat'],
            ['id' => 452, 'pj_id' => null, 'provinsi_id' => 30, 'nama' => 'Kab. Halmahera Tengah'],
            ['id' => 453, 'pj_id' => null, 'provinsi_id' => 30, 'nama' => 'Kab. Kepulauan Sula'],
            ['id' => 454, 'pj_id' => null, 'provinsi_id' => 30, 'nama' => 'Kab. Halmahera Selatan'],
            ['id' => 455, 'pj_id' => null, 'provinsi_id' => 30, 'nama' => 'Kab. Halmahera Utara'],
            ['id' => 456, 'pj_id' => null, 'provinsi_id' => 30, 'nama' => 'Kab. Halmahera Timur'],
            ['id' => 457, 'pj_id' => null, 'provinsi_id' => 30, 'nama' => 'Kab. Pulau Morotai'],
            ['id' => 458, 'pj_id' => null, 'provinsi_id' => 30, 'nama' => 'Kab. Pulau Taliabu'],
            ['id' => 459, 'pj_id' => null, 'provinsi_id' => 30, 'nama' => 'Kota Ternate'],
            ['id' => 460, 'pj_id' => null, 'provinsi_id' => 30, 'nama' => 'Kota Tidore Kepulauan'],
            // papua
            ['id' => 461, 'pj_id' => null, 'provinsi_id' => 31, 'nama' => 'Kab. Merauke'],
            ['id' => 462, 'pj_id' => null, 'provinsi_id' => 31, 'nama' => 'Kab. Jayawijaya'],
            ['id' => 463, 'pj_id' => null, 'provinsi_id' => 31, 'nama' => 'Kab. Jayapura'],
            ['id' => 464, 'pj_id' => null, 'provinsi_id' => 31, 'nama' => 'Kab. Nabire'],
            ['id' => 465, 'pj_id' => null, 'provinsi_id' => 31, 'nama' => 'Kab. Kepulauan Yapen'],
            ['id' => 466, 'pj_id' => null, 'provinsi_id' => 31, 'nama' => 'Kab. Biak Numfor'],
            ['id' => 467, 'pj_id' => null, 'provinsi_id' => 31, 'nama' => 'Kab. Paniai'],
            ['id' => 468, 'pj_id' => null, 'provinsi_id' => 31, 'nama' => 'Kab. Puncak Jaya'],
            ['id' => 469, 'pj_id' => null, 'provinsi_id' => 31, 'nama' => 'Kab. Mimika'],
            ['id' => 470, 'pj_id' => null, 'provinsi_id' => 31, 'nama' => 'Kab. Boven Digoel'],
            ['id' => 471, 'pj_id' => null, 'provinsi_id' => 31, 'nama' => 'Kab. Mappi'],
            ['id' => 472, 'pj_id' => null, 'provinsi_id' => 31, 'nama' => 'Kab. Asmat'],
            ['id' => 473, 'pj_id' => null, 'provinsi_id' => 31, 'nama' => 'Kab. Yahukimo'],
            ['id' => 474, 'pj_id' => null, 'provinsi_id' => 31, 'nama' => 'Kab Pegunungan Bintang'],
            ['id' => 475, 'pj_id' => null, 'provinsi_id' => 31, 'nama' => 'Kab. Tolikara'],
            ['id' => 476, 'pj_id' => null, 'provinsi_id' => 31, 'nama' => 'Kab. Sarmi'],
            ['id' => 477, 'pj_id' => null, 'provinsi_id' => 31, 'nama' => 'Kab. Keerom'],
            ['id' => 478, 'pj_id' => null, 'provinsi_id' => 31, 'nama' => 'Kab. Waropen'],
            ['id' => 479, 'pj_id' => null, 'provinsi_id' => 31, 'nama' => 'Kab. Supiori'],
            ['id' => 480, 'pj_id' => null, 'provinsi_id' => 31, 'nama' => 'Kab. Mamberamo Raya'],
            ['id' => 481, 'pj_id' => null, 'provinsi_id' => 31, 'nama' => 'Kab. Nduga'],
            ['id' => 482, 'pj_id' => null, 'provinsi_id' => 31, 'nama' => 'Kab. Lanny Jaya'],
            ['id' => 483, 'pj_id' => null, 'provinsi_id' => 31, 'nama' => 'Kab. Mamberamo Tengah'],
            ['id' => 484, 'pj_id' => null, 'provinsi_id' => 31, 'nama' => 'Kab. Yalimo'],
            ['id' => 485, 'pj_id' => null, 'provinsi_id' => 31, 'nama' => 'Kab. Puncak'],
            ['id' => 486, 'pj_id' => null, 'provinsi_id' => 31, 'nama' => 'Kab. Dogiyai'],
            ['id' => 487, 'pj_id' => null, 'provinsi_id' => 31, 'nama' => 'Kab. Intan Jaya'],
            ['id' => 488, 'pj_id' => null, 'provinsi_id' => 31, 'nama' => 'Kab. Deiyai'],
            ['id' => 489, 'pj_id' => null, 'provinsi_id' => 31, 'nama' => 'Kota Jayapura'],
            // papua barat
            ['id' => 490, 'pj_id' => null, 'provinsi_id' => 32, 'nama' => 'Kab. Fak Fak'],
            ['id' => 491, 'pj_id' => null, 'provinsi_id' => 32, 'nama' => 'Kab. Kaimana'],
            ['id' => 492, 'pj_id' => null, 'provinsi_id' => 32, 'nama' => 'Kab. Teluk Wondama'],
            ['id' => 493, 'pj_id' => null, 'provinsi_id' => 32, 'nama' => 'Kab. Teluk Bintuni'],
            ['id' => 494, 'pj_id' => null, 'provinsi_id' => 32, 'nama' => 'Kab. Manokwari'],
            ['id' => 495, 'pj_id' => null, 'provinsi_id' => 32, 'nama' => 'Kab. Sorong Selatan'],
            ['id' => 496, 'pj_id' => null, 'provinsi_id' => 32, 'nama' => 'Kab. Sorong'],
            ['id' => 497, 'pj_id' => null, 'provinsi_id' => 32, 'nama' => 'Kab. Raja Ampat'],
            ['id' => 498, 'pj_id' => null, 'provinsi_id' => 32, 'nama' => 'Kab. Tambrauw'],
            ['id' => 499, 'pj_id' => null, 'provinsi_id' => 32, 'nama' => 'Kab. Maybrat'],
            ['id' => 500, 'pj_id' => null, 'provinsi_id' => 32, 'nama' => 'Kab. Manokwari Selatan'],
            ['id' => 501, 'pj_id' => null, 'provinsi_id' => 32, 'nama' => 'Kab. Pegunungan Arfak'],
            ['id' => 502, 'pj_id' => null, 'provinsi_id' => 32, 'nama' => 'Kota Sorong'],
            // papua selatan
            ['id' => 503, 'pj_id' => null, 'provinsi_id' => 33, 'nama' => 'Kab.Merauke'],
            ['id' => 504, 'pj_id' => null, 'provinsi_id' => 33, 'nama' => 'Kab. Asmat'],
            ['id' => 505, 'pj_id' => null, 'provinsi_id' => 33, 'nama' => 'Kab. Boven Digoel'],
            ['id' => 506, 'pj_id' => null, 'provinsi_id' => 33, 'nama' => 'Kab. Mappi'],
            // papua tengah
            ['id' => 507, 'pj_id' => null, 'provinsi_id' => 34, 'nama' => 'Kab. Mimika'],
            ['id' => 508, 'pj_id' => null, 'provinsi_id' => 34, 'nama' => 'Kab. Intan Jaya'],
            ['id' => 509, 'pj_id' => null, 'provinsi_id' => 34, 'nama' => 'Kab. Paniai'],
            ['id' => 510, 'pj_id' => null, 'provinsi_id' => 34, 'nama' => 'Kab  Puncak'],
            ['id' => 512, 'pj_id' => null, 'provinsi_id' => 34, 'nama' => 'Kab. Puncak Jaya'],
            ['id' => 513, 'pj_id' => null, 'provinsi_id' => 34, 'nama' => 'Kab. Nabire'],
            ['id' => 514, 'pj_id' => null, 'provinsi_id' => 34, 'nama' => 'Kab. Dogiyai'],
            ['id' => 515, 'pj_id' => null, 'provinsi_id' => 34, 'nama' => 'Kab. Deiyai'],
            // papua barat daya
            ['id' => 516, 'pj_id' => null, 'provinsi_id' => 35, 'nama' => 'Kab. Maybrat'],
            ['id' => 517, 'pj_id' => null, 'provinsi_id' => 35, 'nama' => 'Kab. Tambrauw'],
            ['id' => 518, 'pj_id' => null, 'provinsi_id' => 35, 'nama' => 'Kab. Sorong'],
            ['id' => 519, 'pj_id' => null, 'provinsi_id' => 35, 'nama' => 'Kota Sorong'],
            ['id' => 520, 'pj_id' => null, 'provinsi_id' => 35, 'nama' => 'Kab. Raja Ampat'],
            ['id' => 521, 'pj_id' => null, 'provinsi_id' => 35, 'nama' => 'Kab. Sorong Selatan'],
        ];

        DB::table('kabupaten')->insert($kabupaten);
    }
}
