<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class KecamatanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $kecamatan = [
            ['kabupaten_id' => 1, 'nama' => 'Alafan'],
            ['kabupaten_id' => 1, 'nama' => 'Salang'],
            ['kabupaten_id' => 1, 'nama' => 'Simeulue Barat'],
            ['kabupaten_id' => 1, 'nama' => 'Simeulue Cut'],
            ['kabupaten_id' => 1, 'nama' => 'Teupah Selatan'],
            ['kabupaten_id' => 1, 'nama' => 'Simeulue Timur'],
            ['kabupaten_id' => 1, 'nama' => 'Teupah Barat'],
            ['kabupaten_id' => 1, 'nama' => 'Teupah Tengah'],
            ['kabupaten_id' => 1, 'nama' => 'Simeulue Tengah'],
            ['kabupaten_id' => 1, 'nama' => 'Teluk Dalam'],
            ['kabupaten_id' => 2, 'nama' => 'Pulau Banyak'],
            ['kabupaten_id' => 2, 'nama' => 'Pulau Banyak Barat'],
            ['kabupaten_id' => 2, 'nama' => 'Singkil'],
            ['kabupaten_id' => 2, 'nama' => 'Singkil Utara'],
            ['kabupaten_id' => 2, 'nama' => 'Kuala Baru'],
            ['kabupaten_id' => 2, 'nama' => 'Simpang Kanan'],
            ['kabupaten_id' => 2, 'nama' => 'Gunung Meriah'],
            ['kabupaten_id' => 2, 'nama' => 'Danau Paris'],
            ['kabupaten_id' => 2, 'nama' => 'Suro'],
            ['kabupaten_id' => 2, 'nama' => 'Singkohor'],
            ['kabupaten_id' => 2, 'nama' => 'Kota Baharu'],
            ['kabupaten_id' => 3, 'nama' => 'Trumon'],
            ['kabupaten_id' => 3, 'nama' => 'Trumon Timur'],
            ['kabupaten_id' => 3, 'nama' => 'Trumon Tengah'],
            ['kabupaten_id' => 3, 'nama' => 'Bakongan'],
            ['kabupaten_id' => 3, 'nama' => 'Bakongan Timur'],
            ['kabupaten_id' => 3, 'nama' => 'Kota Bahagia'],
            ['kabupaten_id' => 3, 'nama' => 'Kluet Selatan'],
            ['kabupaten_id' => 3, 'nama' => 'Kluet Timur'],
            ['kabupaten_id' => 3, 'nama' => 'Kluet Utara'],
            ['kabupaten_id' => 3, 'nama' => 'Pasie Raja'],
            ['kabupaten_id' => 3, 'nama' => 'Kluet Tengah'],
            ['kabupaten_id' => 3, 'nama' => 'Tapak Tuan'],
            ['kabupaten_id' => 3, 'nama' => 'Sama Dua'],
            ['kabupaten_id' => 3, 'nama' => 'Sawang'],
            ['kabupaten_id' => 3, 'nama' => 'Maeukek'],
            ['kabupaten_id' => 3, 'nama' => 'Labuhan Baji'],
            ['kabupaten_id' => 3, 'nama' => 'Labuhan Baji Timur'],
            ['kabupaten_id' => 3, 'nama' => 'Labuhan Baji Barat'],
            ['kabupaten_id' => 4, 'nama' => 'Lawe Alas'],
            ['kabupaten_id' => 4, 'nama' => 'Babul Rahmad'],
            ['kabupaten_id' => 4, 'nama' => 'Tanoh Alas'],
            ['kabupaten_id' => 4, 'nama' => 'Lawe Sigala-Gala'],
            ['kabupaten_id' => 4, 'nama' => 'Babul Makmur'],
            ['kabupaten_id' => 4, 'nama' => 'Semadam'],
            ['kabupaten_id' => 4, 'nama' => 'Lauser'],
            ['kabupaten_id' => 4, 'nama' => 'Bambel'],
            ['kabupaten_id' => 4, 'nama' => 'Bukit Tusam'],
            ['kabupaten_id' => 4, 'nama' => 'Lawe Sumur'],
            ['kabupaten_id' => 4, 'nama' => 'Badar'],
            ['kabupaten_id' => 4, 'nama' => 'Darul Hasanah'],
            ['kabupaten_id' => 4, 'nama' => 'Ketambe'],
            ['kabupaten_id' => 4, 'nama' => 'Deleng Pokhkisen'],
            ['kabupaten_id' => 4, 'nama' => 'Lawe Bulan'],
            ['kabupaten_id' => 5, 'nama' => 'Serba Jadi'],
            ['kabupaten_id' => 5, 'nama' => 'Simpang Jernih'],
            ['kabupaten_id' => 5, 'nama' => 'Peunaron'],
            ['kabupaten_id' => 5, 'nama' => 'Birem Bayeun'],
            ['kabupaten_id' => 5, 'nama' => 'Rantau Selamat'],
            ['kabupaten_id' => 5, 'nama' => 'Sungai Raya'],
            ['kabupaten_id' => 5, 'nama' => 'Perureulak'],
            ['kabupaten_id' => 5, 'nama' => 'Perureulak Timur'],
            ['kabupaten_id' => 5, 'nama' => 'Perureulak Barat'],
            ['kabupaten_id' => 5, 'nama' => 'Ranto Peureulak'],
            ['kabupaten_id' => 5, 'nama' => 'Idi Rayeuk'],
            ['kabupaten_id' => 5, 'nama' => 'Peudawa'],
            ['kabupaten_id' => 5, 'nama' => 'Banda Alam'],
            ['kabupaten_id' => 5, 'nama' => 'Idi Tunong'],
            ['kabupaten_id' => 5, 'nama' => 'Darul Ihsan'],
            ['kabupaten_id' => 5, 'nama' => 'Idi Timur'],
            ['kabupaten_id' => 5, 'nama' => 'Darul Aman'],
            ['kabupaten_id' => 5, 'nama' => 'Nurussalam'],
            ['kabupaten_id' => 5, 'nama' => 'Darul Falah'],
            ['kabupaten_id' => 5, 'nama' => 'Julok'],
            ['kabupaten_id' => 5, 'nama' => 'Indra Makmur'],
            ['kabupaten_id' => 5, 'nama' => 'Pante Bidari'],
            ['kabupaten_id' => 5, 'nama' => 'Simpang Ulim'],
            ['kabupaten_id' => 5, 'nama' => 'Madat'],
            ['kabupaten_id' => 6, 'nama' => 'Linge'],
            ['kabupaten_id' => 6, 'nama' => 'Atu Lintang'],
            ['kabupaten_id' => 6, 'nama' => 'Jagong Jeget'],
            ['kabupaten_id' => 6, 'nama' => 'Bintang'],
            ['kabupaten_id' => 6, 'nama' => 'Lut Tawar'],
            ['kabupaten_id' => 6, 'nama' => 'Kebayakan'],
            ['kabupaten_id' => 6, 'nama' => 'Pegasing'],
            ['kabupaten_id' => 6, 'nama' => 'Bies'],
            ['kabupaten_id' => 6, 'nama' => 'Bebesen'],
            ['kabupaten_id' => 6, 'nama' => 'Kute Panang'],
            ['kabupaten_id' => 6, 'nama' => 'Silih Nara'],
            ['kabupaten_id' => 6, 'nama' => 'Ketol'],
            ['kabupaten_id' => 6, 'nama' => 'Celala'],
            ['kabupaten_id' => 6, 'nama' => 'Rusip Antara'],
            ['kabupaten_id' => 7, 'nama' => 'Johan Pahlawan'],
            ['kabupaten_id' => 7, 'nama' => 'Samatiga'],
            ['kabupaten_id' => 7, 'nama' => 'Bubon'],
            ['kabupaten_id' => 7, 'nama' => 'Arongan Lambalek'],
            ['kabupaten_id' => 7, 'nama' => 'Woyla'],
            ['kabupaten_id' => 7, 'nama' => 'Woyla Barat'],
            ['kabupaten_id' => 7, 'nama' => 'Woyla Timur'],
            ['kabupaten_id' => 7, 'nama' => 'Kaway Xvi'],
            ['kabupaten_id' => 7, 'nama' => 'Meureubo'],
            ['kabupaten_id' => 7, 'nama' => 'Pantai Ceuremen'],
            ['kabupaten_id' => 7, 'nama' => 'Panton Reu'],
            ['kabupaten_id' => 7, 'nama' => 'Sungai Mas'],
            ['kabupaten_id' => 8, 'nama' => 'Lhoong'],
            ['kabupaten_id' => 8, 'nama' => 'Lhoknga'],
            ['kabupaten_id' => 8, 'nama' => 'Indrapuri'],
            ['kabupaten_id' => 8, 'nama' => 'Kuta Cot Glie'],
            ['kabupaten_id' => 8, 'nama' => 'Seulimeum'],
            ['kabupaten_id' => 8, 'nama' => 'Kota Jantho'],
            ['kabupaten_id' => 8, 'nama' => 'Lembah Seulawah'],
            ['kabupaten_id' => 8, 'nama' => 'Darussalam'],
            ['kabupaten_id' => 8, 'nama' => 'Baitussalam'],
            ['kabupaten_id' => 8, 'nama' => 'Kuta Baro'],
            ['kabupaten_id' => 8, 'nama' => 'Montasik'],
            ['kabupaten_id' => 8, 'nama' => 'Blang Bintang'],
            ['kabupaten_id' => 8, 'nama' => 'Ingin Jaya'],
            ['kabupaten_id' => 8, 'nama' => 'Suka Makmur'],
            ['kabupaten_id' => 8, 'nama' => 'Kuta Malaka'],
            ['kabupaten_id' => 8, 'nama' => 'Simpang Tiga'],
            ['kabupaten_id' => 8, 'nama' => 'Darul Imarah'],
            ['kabupaten_id' => 8, 'nama' => 'Peukan Bada'],
            ['kabupaten_id' => 8, 'nama' => 'Darul Kamal'],
            ['kabupaten_id' => 8, 'nama' => 'Pulo Aceh'],
            ['kabupaten_id' => 8, 'nama' => 'Krueng Barona Jaya'],
            ['kabupaten_id' => 8, 'nama' => 'Leupung'],
            ['kabupaten_id' => 9, 'nama' => 'Geumpang'],
            ['kabupaten_id' => 9, 'nama' => 'Mane'],
            ['kabupaten_id' => 9, 'nama' => 'Glumpang Tiga'],
            ['kabupaten_id' => 9, 'nama' => 'Glumpang Baro'],
            ['kabupaten_id' => 9, 'nama' => 'Mutiara'],
            ['kabupaten_id' => 9, 'nama' => 'Mutiara Timur'],
            ['kabupaten_id' => 9, 'nama' => 'Tiro/Truseb'],
            ['kabupaten_id' => 9, 'nama' => 'Tangse'],
            ['kabupaten_id' => 9, 'nama' => 'Keumala'],
            ['kabupaten_id' => 9, 'nama' => 'Titeue'],
            ['kabupaten_id' => 9, 'nama' => 'Sakti'],
            ['kabupaten_id' => 9, 'nama' => 'Mila'],
            ['kabupaten_id' => 9, 'nama' => 'Padang Tiji'],
            ['kabupaten_id' => 9, 'nama' => 'Delima'],
            ['kabupaten_id' => 9, 'nama' => 'Grong Grong'],
            ['kabupaten_id' => 9, 'nama' => 'Indrajaya'],
            ['kabupaten_id' => 9, 'nama' => 'Peukan Baro'],
            ['kabupaten_id' => 9, 'nama' => 'Kembang Tanjong'],
            ['kabupaten_id' => 9, 'nama' => 'Simpang Tiga'],
            ['kabupaten_id' => 9, 'nama' => 'Kota Sigli'],
            ['kabupaten_id' => 9, 'nama' => 'Pidie'],
            ['kabupaten_id' => 9, 'nama' => 'Batee'],
            ['kabupaten_id' => 9, 'nama' => 'Muara Tiga'],
            ['kabupaten_id' => 10, 'nama' => 'Samalanga'],
            ['kabupaten_id' => 10, 'nama' => 'Simpang Mamplam'],
            ['kabupaten_id' => 10, 'nama' => 'Pandrah'],
            ['kabupaten_id' => 10, 'nama' => 'Jeunieb'],
            ['kabupaten_id' => 10, 'nama' => 'Peulimbang'],
            ['kabupaten_id' => 10, 'nama' => 'Peudada'],
            ['kabupaten_id' => 10, 'nama' => 'Juli'],
            ['kabupaten_id' => 10, 'nama' => 'Jeumpa'],
            ['kabupaten_id' => 10, 'nama' => 'Kota Juang'],
            ['kabupaten_id' => 10, 'nama' => 'Kuala'],
            ['kabupaten_id' => 10, 'nama' => 'Jangka'],
            ['kabupaten_id' => 10, 'nama' => 'Peusangan'],
            ['kabupaten_id' => 10, 'nama' => 'Peusangan Selatan'],
            ['kabupaten_id' => 10, 'nama' => 'Peusangan Siblah Krueng'],
            ['kabupaten_id' => 10, 'nama' => 'Makmur'],
            ['kabupaten_id' => 10, 'nama' => 'Ganda Pura'],
            ['kabupaten_id' => 10, 'nama' => 'Kuta Blang'],
            ['kabupaten_id' => 11, 'nama' => 'Sawang'],
            ['kabupaten_id' => 11, 'nama' => 'Nisam'],
            ['kabupaten_id' => 11, 'nama' => 'Nisam Antara'],
            ['kabupaten_id' => 11, 'nama' => 'Banda Baro'],
            ['kabupaten_id' => 11, 'nama' => 'Kuta Makmur'],
            ['kabupaten_id' => 11, 'nama' => 'Simpang Keramat'],
            ['kabupaten_id' => 11, 'nama' => 'Syamtalira Bayu'],
            ['kabupaten_id' => 11, 'nama' => 'Geureudong Pase'],
            ['kabupaten_id' => 11, 'nama' => 'Meurah Mulia'],
            ['kabupaten_id' => 11, 'nama' => 'Matangkuli'],
            ['kabupaten_id' => 11, 'nama' => 'Paya Bakong'],
            ['kabupaten_id' => 11, 'nama' => 'Pirak Timu'],
            ['kabupaten_id' => 11, 'nama' => 'Cot Girek'],
            ['kabupaten_id' => 11, 'nama' => 'Tanah Jambo Aye'],
            ['kabupaten_id' => 11, 'nama' => 'Langkahan'],
            ['kabupaten_id' => 11, 'nama' => 'Seunudon'],
            ['kabupaten_id' => 11, 'nama' => 'Baktiya'],
            ['kabupaten_id' => 11, 'nama' => 'Baktiya Barat'],
            ['kabupaten_id' => 11, 'nama' => 'Lhoksukon'],
            ['kabupaten_id' => 11, 'nama' => 'Tanah Luas'],
            ['kabupaten_id' => 11, 'nama' => 'Nibong'],
            ['kabupaten_id' => 11, 'nama' => 'Samudera'],
            ['kabupaten_id' => 11, 'nama' => 'Syamtalira Aron'],
            ['kabupaten_id' => 11, 'nama' => 'Tanah Pasir'],
            ['kabupaten_id' => 11, 'nama' => 'Lapang'],
            ['kabupaten_id' => 11, 'nama' => 'Muara Batu'],
            ['kabupaten_id' => 11, 'nama' => 'Dewantara'],
            ['kabupaten_id' => 12, 'nama' => 'Manggeng'],
            ['kabupaten_id' => 12, 'nama' => 'Lembah Sabil'],
            ['kabupaten_id' => 12, 'nama' => 'Tangan-Tangan'],
            ['kabupaten_id' => 12, 'nama' => 'Setia'],
            ['kabupaten_id' => 12, 'nama' => 'Blang Pidie'],
            ['kabupaten_id' => 12, 'nama' => 'Jeumpa'],
            ['kabupaten_id' => 12, 'nama' => 'Susoh'],
            ['kabupaten_id' => 12, 'nama' => 'Kuala Batee'],
            ['kabupaten_id' => 12, 'nama' => 'Babeh Rot'],
            ['kabupaten_id' => 13, 'nama' => 'Kuta Panjang'],
            ['kabupaten_id' => 13, 'nama' => 'Blang Jerango'],
            ['kabupaten_id' => 13, 'nama' => 'Blangkejeren'],
            ['kabupaten_id' => 13, 'nama' => 'Putri Betung'],
            ['kabupaten_id' => 13, 'nama' => 'Dabun Gelang'],
            ['kabupaten_id' => 13, 'nama' => 'Blang Pegayon'],
            ['kabupaten_id' => 13, 'nama' => 'Pining'],
            ['kabupaten_id' => 13, 'nama' => 'Pantan Cuaca'],
            ['kabupaten_id' => 13, 'nama' => 'Rikit Gaib'],
            ['kabupaten_id' => 13, 'nama' => 'Terangun'],
            ['kabupaten_id' => 13, 'nama' => 'Tripe Jaya'],
            ['kabupaten_id' => 14, 'nama' => 'Tamiang Hulu'],
            ['kabupaten_id' => 14, 'nama' => 'Bandar Pusaka'],
            ['kabupaten_id' => 14, 'nama' => 'Kejuruan Muda'],
            ['kabupaten_id' => 14, 'nama' => 'Tenggulun'],
            ['kabupaten_id' => 14, 'nama' => 'Rantau'],
            ['kabupaten_id' => 14, 'nama' => 'Seruway'],
            ['kabupaten_id' => 14, 'nama' => 'Bendahara'],
            ['kabupaten_id' => 14, 'nama' => 'Manyak Payed'],
            ['kabupaten_id' => 14, 'nama' => 'Banda Mulia'],
            ['kabupaten_id' => 14, 'nama' => 'Karang Baru'],
            ['kabupaten_id' => 14, 'nama' => 'Sekerak'],
            ['kabupaten_id' => 15, 'nama' => 'Darul Makmur'],
            ['kabupaten_id' => 15, 'nama' => 'Tripa Makmur'],
            ['kabupaten_id' => 15, 'nama' => 'Kuala'],
            ['kabupaten_id' => 15, 'nama' => 'Kuala Pesisir'],
            ['kabupaten_id' => 15, 'nama' => 'Tadu Raya'],
            ['kabupaten_id' => 15, 'nama' => 'Beutong'],
            ['kabupaten_id' => 15, 'nama' => 'Beutong Ateuh Banggalang'],
            ['kabupaten_id' => 15, 'nama' => 'Seunagan'],
            ['kabupaten_id' => 15, 'nama' => 'Suka Makmue'],
            ['kabupaten_id' => 15, 'nama' => 'Seunagan Timur'],
            ['kabupaten_id' => 16, 'nama' => 'Teunom'],
            ['kabupaten_id' => 16, 'nama' => 'Pasie Raya'],
            ['kabupaten_id' => 16, 'nama' => 'Panga'],
            ['kabupaten_id' => 16, 'nama' => 'Krueng Sabee'],
            ['kabupaten_id' => 16, 'nama' => 'Setia Bakti'],
            ['kabupaten_id' => 16, 'nama' => 'Sampoiniet'],
            ['kabupaten_id' => 16, 'nama' => 'Darul Hikmah'],
            ['kabupaten_id' => 16, 'nama' => 'Jaya'],
            ['kabupaten_id' => 16, 'nama' => 'Indra Jaya'],
            ['kabupaten_id' => 17, 'nama' => 'Timang Gajah'],
            ['kabupaten_id' => 17, 'nama' => 'Gajah Putih'],
            ['kabupaten_id' => 17, 'nama' => 'Pintu Rime Gayo'],
            ['kabupaten_id' => 17, 'nama' => 'Bukit'],
            ['kabupaten_id' => 17, 'nama' => 'Wih Pesam'],
            ['kabupaten_id' => 17, 'nama' => 'Bandar'],
            ['kabupaten_id' => 17, 'nama' => 'Bener Kelipah'],
            ['kabupaten_id' => 17, 'nama' => 'Syiah Utama'],
            ['kabupaten_id' => 17, 'nama' => 'Mesidah'],
            ['kabupaten_id' => 17, 'nama' => 'Permata'],
            ['kabupaten_id' => 18, 'nama' => 'Meureudu'],
            ['kabupaten_id' => 18, 'nama' => 'Meurah Dua'],
            ['kabupaten_id' => 18, 'nama' => 'Bandar Dua'],
            ['kabupaten_id' => 18, 'nama' => 'Jangka Buya'],
            ['kabupaten_id' => 18, 'nama' => 'Ulim'],
            ['kabupaten_id' => 18, 'nama' => 'Trienggadeng'],
            ['kabupaten_id' => 18, 'nama' => 'Panteraja'],
            ['kabupaten_id' => 18, 'nama' => 'Bandar Baru'],
            ['kabupaten_id' => 19, 'nama' => 'Meuraxa'],
            ['kabupaten_id' => 19, 'nama' => 'Banda Raya'],
            ['kabupaten_id' => 19, 'nama' => 'Syiah Kuala'],
            ['kabupaten_id' => 19, 'nama' => 'Lueng Bata'],
            ['kabupaten_id' => 19, 'nama' => 'Ulee Kareng'],
            ['kabupaten_id' => 20, 'nama' => 'Sukajaya'],
            ['kabupaten_id' => 20, 'nama' => 'Sukakarya'],
            ['kabupaten_id' => 21, 'nama' => 'Langsa Timur'],
            ['kabupaten_id' => 21, 'nama' => 'Langsa Lama'],
            ['kabupaten_id' => 21, 'nama' => 'Langsa Barat'],
            ['kabupaten_id' => 22, 'nama' => 'Blang Mangat'],
            ['kabupaten_id' => 22, 'nama' => 'Muara Dua'],
            ['kabupaten_id' => 22, 'nama' => 'Muara Satu'],
            ['kabupaten_id' => 23, 'nama' => 'Simpang Kiri'],
            ['kabupaten_id' => 23, 'nama' => 'Penanggalan'],
            ['kabupaten_id' => 23, 'nama' => 'Rundeng'],
            ['kabupaten_id' => 23, 'nama' => 'Sultan Daulat'],
            ['kabupaten_id' => 23, 'nama' => 'Longkib'],
            ['kabupaten_id' => 24, 'nama' => "Idano Gawo"],
            ['kabupaten_id' => 24, 'nama' => "Bawolato"],
            ['kabupaten_id' => 24, 'nama' => "Ulugawo"],
            ['kabupaten_id' => 24, 'nama' => "Gido"],
            ['kabupaten_id' => 24, 'nama' => "Sogaeadu"],
            ['kabupaten_id' => 24, 'nama' => "Ma U"],
            ['kabupaten_id' => 24, 'nama' => "Somolo-Molo"],
            ['kabupaten_id' => 24, 'nama' => "Hiliduho"],
            ['kabupaten_id' => 24, 'nama' => "Hili Serangkai"],
            ['kabupaten_id' => 24, 'nama' => "Botomuzoi"],
            ['kabupaten_id' => 25, 'nama' => "Batahan"],
            ['kabupaten_id' => 25, 'nama' => "Sinunukan"],
            ['kabupaten_id' => 25, 'nama' => "Batang Natal"],
            ['kabupaten_id' => 25, 'nama' => "Lingga Bayu"],
            ['kabupaten_id' => 25, 'nama' => "Ranto Baek"],
            ['kabupaten_id' => 25, 'nama' => "Kotanopan"],
            ['kabupaten_id' => 25, 'nama' => "Ulu Pungkut"],
            ['kabupaten_id' => 25, 'nama' => "Tambangan"],
            ['kabupaten_id' => 25, 'nama' => "Lembah Sorik Marapi"],
            ['kabupaten_id' => 25, 'nama' => "Puncak Sorik Marapi"],
            ['kabupaten_id' => 25, 'nama' => "Muara Sipongi"],
            ['kabupaten_id' => 25, 'nama' => "Pakantan"],
            ['kabupaten_id' => 25, 'nama' => "Panyabungan"],
            ['kabupaten_id' => 25, 'nama' => "Panyabungan Selatan"],
            ['kabupaten_id' => 25, 'nama' => "Panyabungan Barat"],
            ['kabupaten_id' => 25, 'nama' => "Panyabungan Utara"],
            ['kabupaten_id' => 25, 'nama' => "Panyabungan Timur"],
            ['kabupaten_id' => 25, 'nama' => "Huta Bargot"],
            ['kabupaten_id' => 25, 'nama' => "Natal"],
            ['kabupaten_id' => 25, 'nama' => "Muara Batang Gadis"],
            ['kabupaten_id' => 25, 'nama' => "Siabu"],
            ['kabupaten_id' => 25, 'nama' => "Bukit Malintang"],
            ['kabupaten_id' => 25, 'nama' => "Naga Juang"],
            ['kabupaten_id' => 26, 'nama' => "Batang Angkola"],
            ['kabupaten_id' => 26, 'nama' => "Sayur Matinggi"],
            ['kabupaten_id' => 26, 'nama' => "Tano Tombangan Angkola"],
            ['kabupaten_id' => 26, 'nama' => "Angkola Timur"],
            ['kabupaten_id' => 26, 'nama' => "Angkola Selatan"],
            ['kabupaten_id' => 26, 'nama' => "Angkola Barat"],
            ['kabupaten_id' => 26, 'nama' => "Angkola Sangkunur"],
            ['kabupaten_id' => 26, 'nama' => "Batang Toru"],
            ['kabupaten_id' => 26, 'nama' => "Marancar"],
            ['kabupaten_id' => 26, 'nama' => "Muara Batang Toru"],
            ['kabupaten_id' => 26, 'nama' => "Sipirok"],
            ['kabupaten_id' => 26, 'nama' => "Arse"],
            ['kabupaten_id' => 26, 'nama' => "Saipar Dolok Hole"],
            ['kabupaten_id' => 26, 'nama' => "Aek Bilah"],
            ['kabupaten_id' => 27, 'nama' => "Badiri"],
            ['kabupaten_id' => 27, 'nama' => "Sibabangun"],
            ['kabupaten_id' => 27, 'nama' => "Pandan"],
            ['kabupaten_id' => 27, 'nama' => "Tapian Nauli"],
            ['kabupaten_id' => 27, 'nama' => "Sorkam"],
            ['kabupaten_id' => 27, 'nama' => "Sosor Gadong"],
            ['kabupaten_id' => 27, 'nama' => "Andam Dewi"],
            ['kabupaten_id' => 27, 'nama' => "Manduamas"],
            ['kabupaten_id' => 27, 'nama' => "Sirandorung"],
            ['kabupaten_id' => 27, 'nama' => "Kolang"],
            ['kabupaten_id' => 27, 'nama' => "Pasaribu Tobing"],
            ['kabupaten_id' => 28, 'nama' => "Parmonangan"],
            ['kabupaten_id' => 28, 'nama' => "Adian Koting"],
            ['kabupaten_id' => 28, 'nama' => "Sipoholon"],
            ['kabupaten_id' => 28, 'nama' => "Tarutung"],
            ['kabupaten_id' => 28, 'nama' => "Siatas Barita"],
            ['kabupaten_id' => 28, 'nama' => "Pahae Julu"],
            ['kabupaten_id' => 28, 'nama' => "Pahae Jae"],
            ['kabupaten_id' => 28, 'nama' => "Purbatua"],
            ['kabupaten_id' => 28, 'nama' => "Simangumban"],
            ['kabupaten_id' => 28, 'nama' => "Pangaribuan"],
            ['kabupaten_id' => 28, 'nama' => "Garoga"],
            ['kabupaten_id' => 28, 'nama' => "Sipahutar"],
            ['kabupaten_id' => 28, 'nama' => "Siborong-Borong"],
            ['kabupaten_id' => 28, 'nama' => "Pagaran"],
            ['kabupaten_id' => 28, 'nama' => "Muara"],
            ['kabupaten_id' => 29, 'nama' => "Balige"],
            ['kabupaten_id' => 29, 'nama' => "Tampahan"],
            ['kabupaten_id' => 29, 'nama' => "Laguboti"],
            ['kabupaten_id' => 29, 'nama' => "Habinsaran"],
            ['kabupaten_id' => 29, 'nama' => "Borbor"],
            ['kabupaten_id' => 29, 'nama' => "Nassau"],
            ['kabupaten_id' => 29, 'nama' => "Silaen"],
            ['kabupaten_id' => 29, 'nama' => "Sigumpar"],
            ['kabupaten_id' => 29, 'nama' => "Porsea"],
            ['kabupaten_id' => 29, 'nama' => "Pintu Pohan Meranti"],
            ['kabupaten_id' => 29, 'nama' => "Siantar Narumonda"],
            ['kabupaten_id' => 29, 'nama' => "Parmaksian"],
            ['kabupaten_id' => 29, 'nama' => "Lumban Julu"],
            ['kabupaten_id' => 29, 'nama' => "Uluan"],
            ['kabupaten_id' => 29, 'nama' => "Ajibata"],
            ['kabupaten_id' => 29, 'nama' => "Bonatua Lunasi"],
            ['kabupaten_id' => 30, 'nama' => "Bilah Hulu"],
            ['kabupaten_id' => 30, 'nama' => "Pangkatan"],
            ['kabupaten_id' => 30, 'nama' => "Bilah Barat"],
            ['kabupaten_id' => 30, 'nama' => "Bilah Hilir"],
            ['kabupaten_id' => 30, 'nama' => "Panai Hulu"],
            ['kabupaten_id' => 30, 'nama' => "Panai Tengah"],
            ['kabupaten_id' => 30, 'nama' => "Panai Hilir"],
            ['kabupaten_id' => 30, 'nama' => "Rantau Selatan"],
            ['kabupaten_id' => 30, 'nama' => "Rantau Utara"],
            ['kabupaten_id' => 31, 'nama' => "Bandar Pulau"],
            ['kabupaten_id' => 31, 'nama' => "Aek Songsongan"],
            ['kabupaten_id' => 31, 'nama' => "Pulau Rakyat"],
            ['kabupaten_id' => 31, 'nama' => "Aek Kuasan"],
            ['kabupaten_id' => 31, 'nama' => "Aek Ledong"],
            ['kabupaten_id' => 31, 'nama' => "Sei Kepayang"],
            ['kabupaten_id' => 31, 'nama' => "Sei Kepayang Timur"],
            ['kabupaten_id' => 31, 'nama' => "Tanjung Balai"],
            ['kabupaten_id' => 31, 'nama' => "Simpang Empat"],
            ['kabupaten_id' => 31, 'nama' => "Air Batu"],
            ['kabupaten_id' => 31, 'nama' => "Sei Dadap"],
            ['kabupaten_id' => 31, 'nama' => "Tinggi Raja"],
            ['kabupaten_id' => 31, 'nama' => "Setia Janji"],
            ['kabupaten_id' => 31, 'nama' => "Meranti"],
            ['kabupaten_id' => 31, 'nama' => "Pulo Bandring"],
            ['kabupaten_id' => 31, 'nama' => "Rawang Panca Arga"],
            ['kabupaten_id' => 31, 'nama' => "Air Joman"],
            ['kabupaten_id' => 31, 'nama' => "Silau Laut"],
            ['kabupaten_id' => 31, 'nama' => "Kisaran Timur"],
            ['kabupaten_id' => 32, 'nama' => "Silimakuta"],
            ['kabupaten_id' => 32, 'nama' => "Pematang Silimahuta"],
            ['kabupaten_id' => 32, 'nama' => "Purba"],
            ['kabupaten_id' => 32, 'nama' => "Haranggaol Horison"],
            ['kabupaten_id' => 32, 'nama' => "Dolok Pardamean"],
            ['kabupaten_id' => 32, 'nama' => "Sidamanik"],
            ['kabupaten_id' => 32, 'nama' => "Pematang Sidamanik"],
            ['kabupaten_id' => 32, 'nama' => "Girsang Sipangan Bolon"],
            ['kabupaten_id' => 32, 'nama' => "Tanah Jawa"],
            ['kabupaten_id' => 32, 'nama' => "Hatonduhan"],
            ['kabupaten_id' => 32, 'nama' => "Dolok Panribuan"],
            ['kabupaten_id' => 32, 'nama' => "Jorlang Hataran"],
            ['kabupaten_id' => 32, 'nama' => "Panei"],
            ['kabupaten_id' => 32, 'nama' => "Panombean Panei"],
            ['kabupaten_id' => 32, 'nama' => "Raya"],
            ['kabupaten_id' => 32, 'nama' => "Dolok Silau"],
            ['kabupaten_id' => 32, 'nama' => "Silau Kahean"],
            ['kabupaten_id' => 32, 'nama' => "Raya Kahean"],
            ['kabupaten_id' => 32, 'nama' => "Tapian Dolok"],
            ['kabupaten_id' => 32, 'nama' => "Dolok Batu Nanggar"],
            ['kabupaten_id' => 32, 'nama' => "Siantar"],
            ['kabupaten_id' => 32, 'nama' => "Gunung Malela"],
            ['kabupaten_id' => 32, 'nama' => "Gunung Maligas"],
            ['kabupaten_id' => 32, 'nama' => "Hutabayu Raja"],
            ['kabupaten_id' => 32, 'nama' => "Jawa Maraja Bah Jambi"],
            ['kabupaten_id' => 32, 'nama' => "Pematang Bandar"],
            ['kabupaten_id' => 32, 'nama' => "Bandar Huluan"],
            ['kabupaten_id' => 32, 'nama' => "Bandar"],
            ['kabupaten_id' => 32, 'nama' => "Bandar Masilam"],
            ['kabupaten_id' => 32, 'nama' => "Bosar Maligas"],
            ['kabupaten_id' => 32, 'nama' => "Ujung Padang"],
            ['kabupaten_id' => 32, 'nama' => "Dolok Masagal"],
            ['kabupaten_id' => 33, 'nama' => "Berampu"],
            ['kabupaten_id' => 33, 'nama' => "Sitinjo"],
            ['kabupaten_id' => 33, 'nama' => "Parbuluan"],
            ['kabupaten_id' => 33, 'nama' => "Sumbul"],
            ['kabupaten_id' => 33, 'nama' => "Lae Parira"],
            ['kabupaten_id' => 33, 'nama' => "Siempat Nempu"],
            ['kabupaten_id' => 33, 'nama' => "Siempat Nempu Hulu"],
            ['kabupaten_id' => 33, 'nama' => "Siempat Nempu Hilir"],
            ['kabupaten_id' => 33, 'nama' => "Tiga Lingga"],
            ['kabupaten_id' => 33, 'nama' => "TANAH PINEM"],
            ['kabupaten_id' => 33, 'nama' => "GUNUNG SITENGGER"],
            ['kabupaten_id' => 33, 'nama' => "SIDIKALANG"],
            ['kabupaten_id' => 33, 'nama' => "PEGAGAN HILIR"],
            ['kabupaten_id' => 33, 'nama' => "SILIMA PUNGGA 2"],
            ['kabupaten_id' => 34, 'nama' => "Mardingding"],
            ['kabupaten_id' => 34, 'nama' => "Laubaleng"],
            ['kabupaten_id' => 34, 'nama' => "Tiga Binanga"],
            ['kabupaten_id' => 34, 'nama' => "Juhar"],
            ['kabupaten_id' => 34, 'nama' => "Munte"],
            ['kabupaten_id' => 34, 'nama' => "Kuta Buluh"],
            ['kabupaten_id' => 34, 'nama' => "Payung"],
            ['kabupaten_id' => 34, 'nama' => "Tiganderket"],
            ['kabupaten_id' => 34, 'nama' => "Simpang Empat"],
            ['kabupaten_id' => 34, 'nama' => "Naman Teran"],
            ['kabupaten_id' => 34, 'nama' => "Merdeka"],
            ['kabupaten_id' => 34, 'nama' => "Kabanjahe"],
            ['kabupaten_id' => 34, 'nama' => "Berastagi"],
            ['kabupaten_id' => 34, 'nama' => "Tigapanah"],
            ['kabupaten_id' => 34, 'nama' => "Dolat Rayat"],
            ['kabupaten_id' => 34, 'nama' => "Merek"],
            ['kabupaten_id' => 34, 'nama' => "Barusjahe"],
            ['kabupaten_id' => 35, 'nama' => "Pancur Batu"],
            ['kabupaten_id' => 35, 'nama' => "Namo Rambe"],
            ['kabupaten_id' => 35, 'nama' => "Biru-Biru"],
            ['kabupaten_id' => 35, 'nama' => "Bangun Purba"],
            ['kabupaten_id' => 35, 'nama' => "Galang"],
            ['kabupaten_id' => 35, 'nama' => "Tanjung Morawa"],
            ['kabupaten_id' => 35, 'nama' => "Sunggal"],
            ['kabupaten_id' => 35, 'nama' => "Hamparan Perak"],
            ['kabupaten_id' => 35, 'nama' => "Labuhan Deli"],
            ['kabupaten_id' => 35, 'nama' => "Percut Sei Tuan"],
            ['kabupaten_id' => 35, 'nama' => "Batang Kuis"],
            ['kabupaten_id' => 35, 'nama' => "Pantai Labu"],
            ['kabupaten_id' => 35, 'nama' => "Beringin"],
            ['kabupaten_id' => 35, 'nama' => "Lubuk Pakam"],
            ['kabupaten_id' => 35, 'nama' => "Gunung Meriah"],
            ['kabupaten_id' => 35, 'nama' => "Sibolangit"],
            ['kabupaten_id' => 35, 'nama' => "Stm Hilir"],
            ['kabupaten_id' => 35, 'nama' => "Stm Hulu"],
            ['kabupaten_id' => 35, 'nama' => "Patumbak"],
            ['kabupaten_id' => 35, 'nama' => "Deli Tua"],
            ['kabupaten_id' => 35, 'nama' => "Pagar Merbau"],
            ['kabupaten_id' => 36, 'nama' => "Bohorok"],
            ['kabupaten_id' => 36, 'nama' => "Sirapit"],
            ['kabupaten_id' => 36, 'nama' => "Salapian"],
            ['kabupaten_id' => 36, 'nama' => "Kutambaru"],
            ['kabupaten_id' => 36, 'nama' => "Sei Bingai"],
            ['kabupaten_id' => 36, 'nama' => "Kuala"],
            ['kabupaten_id' => 36, 'nama' => "Selesai"],
            ['kabupaten_id' => 36, 'nama' => "Binjai"],
            ['kabupaten_id' => 36, 'nama' => "Stabat"],
            ['kabupaten_id' => 36, 'nama' => "Wampu"],
            ['kabupaten_id' => 36, 'nama' => "Batang Serangan"],
            ['kabupaten_id' => 36, 'nama' => "Sawit Seberang"],
            ['kabupaten_id' => 36, 'nama' => "Padang Tualang"],
            ['kabupaten_id' => 36, 'nama' => "Hinai"],
            ['kabupaten_id' => 36, 'nama' => "Secanggang"],
            ['kabupaten_id' => 36, 'nama' => "Tanjung Pura"],
            ['kabupaten_id' => 36, 'nama' => "Gebang"],
            ['kabupaten_id' => 36, 'nama' => "Babalan"],
            ['kabupaten_id' => 36, 'nama' => "Sei Lepan"],
            ['kabupaten_id' => 36, 'nama' => "Brandan Barat"],
            ['kabupaten_id' => 36, 'nama' => "Besitang"],
            ['kabupaten_id' => 36, 'nama' => "Pangkalan Susu"],
            ['kabupaten_id' => 36, 'nama' => "Pematang Jaya"],
            ['kabupaten_id' => 37, 'nama' => "Pulau-Pulau Batu"],
            ['kabupaten_id' => 37, 'nama' => "Teluk Dalam"],
            ['kabupaten_id' => 37, 'nama' => "Fanayama"],
            ['kabupaten_id' => 37, 'nama' => "Toma"],
            ['kabupaten_id' => 37, 'nama' => "Maniamolo"],
            ['kabupaten_id' => 37, 'nama' => "Mazino"],
            ['kabupaten_id' => 37, 'nama' => "Amandraya"],
            ['kabupaten_id' => 37, 'nama' => "Aramo"],
            ['kabupaten_id' => 37, 'nama' => "Lahusa"],
            ['kabupaten_id' => 37, 'nama' => "Gomo"],
            ['kabupaten_id' => 37, 'nama' => "Mazo"],
            ['kabupaten_id' => 37, 'nama' => "Lolomatua"],
            ['kabupaten_id' => 37, 'nama' => "Lolowa U"],
            ['kabupaten_id' => 37, 'nama' => "Hilimegai"],
            ['kabupaten_id' => 37, 'nama' => "Susua"],
            ['kabupaten_id' => 37, 'nama' => "Umbunasi"],
            ['kabupaten_id' => 37, 'nama' => "Huruna"],
            ['kabupaten_id' => 37, 'nama' => "O'O'U"],
            ['kabupaten_id' => 37, 'nama' => "Ulususua"],
            ['kabupaten_id' => 37, 'nama' => "Sidua'Ori"],
            ['kabupaten_id' => 37, 'nama' => "Somambawa"],
            ['kabupaten_id' => 37, 'nama' => "Boronadu"],
            ['kabupaten_id' => 37, 'nama' => "Luahagundre Maniamolo"],
            ['kabupaten_id' => 37, 'nama' => "Ulu Idanotae"],
            ['kabupaten_id' => 37, 'nama' => "Idanotae"],
            ['kabupaten_id' => 38, 'nama' => "Pakkat"],
            ['kabupaten_id' => 38, 'nama' => "Onan Ganjang"],
            ['kabupaten_id' => 38, 'nama' => "Sijama Polang"],
            ['kabupaten_id' => 38, 'nama' => "Dolok Sanggul"],
            ['kabupaten_id' => 38, 'nama' => "Lintong Nihuta"],
            ['kabupaten_id' => 38, 'nama' => "Paranginan"],
            ['kabupaten_id' => 38, 'nama' => "Bakti Raja"],
            ['kabupaten_id' => 38, 'nama' => "Pollung"],
            ['kabupaten_id' => 38, 'nama' => "Parlilitan"],
            ['kabupaten_id' => 38, 'nama' => "Tara Bintang"],
            ['kabupaten_id' => 39, 'nama' => "Salak"],
            ['kabupaten_id' => 39, 'nama' => "Sitellu Tali Urang Jehe"],
            ['kabupaten_id' => 39, 'nama' => "Pagindar"],
            ['kabupaten_id' => 39, 'nama' => "Sitellu Tali Urang Julu"],
            ['kabupaten_id' => 39, 'nama' => "Pergetteng-Getteng Sengkut"],
            ['kabupaten_id' => 39, 'nama' => "Kerajaan"],
            ['kabupaten_id' => 39, 'nama' => "Tinada"],
            ['kabupaten_id' => 39, 'nama' => "Siempat Rube"],
            ['kabupaten_id' => 40, 'nama' => "Sianjur Mula Mula"],
            ['kabupaten_id' => 40, 'nama' => "Harian"],
            ['kabupaten_id' => 40, 'nama' => "Sitio-Tio"],
            ['kabupaten_id' => 40, 'nama' => "Onan Runggu"],
            ['kabupaten_id' => 40, 'nama' => "Nainggolan"],
            ['kabupaten_id' => 40, 'nama' => "Palipi"],
            ['kabupaten_id' => 40, 'nama' => "Ronggur Nihuta"],
            ['kabupaten_id' => 40, 'nama' => "Pangururan"],
            ['kabupaten_id' => 40, 'nama' => "Simanindo"],
            ['kabupaten_id' => 41, 'nama' => "Dolok Masihul"],
            ['kabupaten_id' => 41, 'nama' => "Serbajadi"],
            ['kabupaten_id' => 41, 'nama' => "Tebingtinggi"],
            ['kabupaten_id' => 41, 'nama' => "Tanjung Beringin"],
            ['kabupaten_id' => 41, 'nama' => "Sei Rampah"],
            ['kabupaten_id' => 41, 'nama' => "Perbaungan"],
            ['kabupaten_id' => 41, 'nama' => "Bandar Khalipah"],
            ['kabupaten_id' => 41, 'nama' => "Pegajahan"],
            ['kabupaten_id' => 41, 'nama' => "Kotarih"],
            ['kabupaten_id' => 41, 'nama' => "Sipispis"],
            ['kabupaten_id' => 41, 'nama' => "Silinda"],
            ['kabupaten_id' => 41, 'nama' => "Dolok Merawan"],
            ['kabupaten_id' => 41, 'nama' => "Tebing Syahbandar"],
            ['kabupaten_id' => 41, 'nama' => "Bintang Bayu"],
            ['kabupaten_id' => 41, 'nama' => "Pantai Cermin"],
            ['kabupaten_id' => 41, 'nama' => "Sei Bamban"],
            ['kabupaten_id' => 41, 'nama' => "Teluk Mengkudu"],
            ['kabupaten_id' => 42, 'nama' => "Sei Balai"],
            ['kabupaten_id' => 42, 'nama' => "Tanjung Tiram"],
            ['kabupaten_id' => 42, 'nama' => "Talawi"],
            ['kabupaten_id' => 42, 'nama' => "Air Putih"],
            ['kabupaten_id' => 42, 'nama' => "Sei Suka"],
            ['kabupaten_id' => 42, 'nama' => "Medang Deras"],
            ['kabupaten_id' => 42, 'nama' => "Lima Puluh Pesisir"],
            ['kabupaten_id' => 42, 'nama' => "Datuk Tanah Datar"],
            ['kabupaten_id' => 42, 'nama' => "Nibung Hangus"],
            ['kabupaten_id' => 42, 'nama' => "Datuk Lima Puluh"],
            ['kabupaten_id' => 43, 'nama' => "Batang Onang"],
            ['kabupaten_id' => 43, 'nama' => "Padang Bolak Julu"],
            ['kabupaten_id' => 43, 'nama' => "Portibi"],
            ['kabupaten_id' => 43, 'nama' => "Padang Bolak"],
            ['kabupaten_id' => 43, 'nama' => "Simangambat"],
            ['kabupaten_id' => 43, 'nama' => "Halongonan"],
            ['kabupaten_id' => 43, 'nama' => "Dolok"],
            ['kabupaten_id' => 43, 'nama' => "Dolok Sigompulon"],
            ['kabupaten_id' => 43, 'nama' => "Hulu Sihapas"],
            ['kabupaten_id' => 44, 'nama' => "Sosopan"],
            ['kabupaten_id' => 44, 'nama' => "Ulu Barumun"],
            ['kabupaten_id' => 44, 'nama' => "Barumun"],
            ['kabupaten_id' => 44, 'nama' => "Barumun Selatan"],
            ['kabupaten_id' => 44, 'nama' => "Lubuk Barumun"],
            ['kabupaten_id' => 44, 'nama' => "Sosa"],
            ['kabupaten_id' => 44, 'nama' => "Batang Lubu Sutam"],
            ['kabupaten_id' => 44, 'nama' => "Huta Raja Tinggi"],
            ['kabupaten_id' => 44, 'nama' => "Huristak"],
            ['kabupaten_id' => 44, 'nama' => "Barumun Tengah"],
            ['kabupaten_id' => 44, 'nama' => "Aek Nabara Barumun"],
            ['kabupaten_id' => 44, 'nama' => "Sihapas Barumun"],
            ['kabupaten_id' => 45, 'nama' => "Sungai Kanan"],
            ['kabupaten_id' => 45, 'nama' => "Torgamba"],
            ['kabupaten_id' => 45, 'nama' => "Kota Pinang"],
            ['kabupaten_id' => 45, 'nama' => "Silangkitang"],
            ['kabupaten_id' => 45, 'nama' => "Kampung Rakyat"],
            ['kabupaten_id' => 46, 'nama' => "Na IX-X"],
            ['kabupaten_id' => 46, 'nama' => "Marbau"],
            ['kabupaten_id' => 46, 'nama' => "Aek Kuo"],
            ['kabupaten_id' => 46, 'nama' => "Aek Natas"],
            ['kabupaten_id' => 46, 'nama' => "Kualuh Selatan"],
            ['kabupaten_id' => 46, 'nama' => "Kualuh Hilir"],
            ['kabupaten_id' => 46, 'nama' => "Kualuh Hulu"],
            ['kabupaten_id' => 46, 'nama' => "Kualuh Leidong"],
            ['kabupaten_id' => 47, 'nama' => "Tugala Oyo"],
            ['kabupaten_id' => 47, 'nama' => "Alasa"],
            ['kabupaten_id' => 47, 'nama' => "Alasa Talu Muzoi"],
            ['kabupaten_id' => 47, 'nama' => "Namohalu Esiwa"],
            ['kabupaten_id' => 47, 'nama' => "Sitolu Ori"],
            ['kabupaten_id' => 47, 'nama' => "Tuhemberua"],
            ['kabupaten_id' => 47, 'nama' => "Sawo"],
            ['kabupaten_id' => 47, 'nama' => "Lotu"],
            ['kabupaten_id' => 47, 'nama' => "Lahewa Timur"],
            ['kabupaten_id' => 47, 'nama' => "Afulu"],
            ['kabupaten_id' => 47, 'nama' => "Lahewa"],
            ['kabupaten_id' => 48, 'nama' => "Sirombu"],
            ['kabupaten_id' => 48, 'nama' => "Lahomi"],
            ['kabupaten_id' => 48, 'nama' => "Ulu Moro O"],
            ['kabupaten_id' => 48, 'nama' => "Lolofitu Moi"],
            ['kabupaten_id' => 48, 'nama' => "Mandrehe Utara"],
            ['kabupaten_id' => 48, 'nama' => "Mandrehe"],
            ['kabupaten_id' => 48, 'nama' => "Mandrehe Barat"],
            ['kabupaten_id' => 48, 'nama' => "Moro O"],
            ['kabupaten_id' => 49, 'nama' => "Medan Amplas"],
            ['kabupaten_id' => 49, 'nama' => "Medan Helvetia"],
            ['kabupaten_id' => 49, 'nama' => "Medan Kota"],
            ['kabupaten_id' => 49, 'nama' => "Medan Sunggal"],
            ['kabupaten_id' => 49, 'nama' => "Medan Deli"],
            ['kabupaten_id' => 49, 'nama' => "Medan Tuntungan"],
            ['kabupaten_id' => 49, 'nama' => "Medan Johor"],
            ['kabupaten_id' => 49, 'nama' => "Medan Marelan"],
            ['kabupaten_id' => 49, 'nama' => "Medan Labuhan"],
            ['kabupaten_id' => 49, 'nama' => "Medan Selayang"],
            ['kabupaten_id' => 50, 'nama' => "Binjai Selatan"],
            ['kabupaten_id' => 50, 'nama' => "Binjai Kota"],
            ['kabupaten_id' => 50, 'nama' => "Binjai Timur"],
            ['kabupaten_id' => 50, 'nama' => "Binjai Utara"],
            ['kabupaten_id' => 50, 'nama' => "Binjai Barat"],
            ['kabupaten_id' => 51, 'nama' => "Gunungsitoli Selatan"],
            ['kabupaten_id' => 51, 'nama' => "Gunungsitoli Barat"],
            ['kabupaten_id' => 51, 'nama' => "Gunung Sitoli"],
            ['kabupaten_id' => 51, 'nama' => "Gunungsitoli Alo Oa"],
            ['kabupaten_id' => 51, 'nama' => "Gunungsitoli Utara"],
            ['kabupaten_id' => 51, 'nama' => "Gunungsitoli Idanoi"],
            ['kabupaten_id' => 52, 'nama' => "Rambutan"],
            ['kabupaten_id' => 52, 'nama' => "Bajenis"],
            ['kabupaten_id' => 53, 'nama' => "Pagai Utara"],
            ['kabupaten_id' => 53, 'nama' => "Sipora Selatan"],
            ['kabupaten_id' => 53, 'nama' => "Siberut Tengah"],
            ['kabupaten_id' => 53, 'nama' => "Siberut Barat"],
            ['kabupaten_id' => 53, 'nama' => "Sipora Utara"],
            ['kabupaten_id' => 53, 'nama' => "Sikakap"],
            ['kabupaten_id' => 54, 'nama' => "Silaut"],
            ['kabupaten_id' => 54, 'nama' => "Lunang"],
            ['kabupaten_id' => 54, 'nama' => "Basa Ampek Balai Tapan"],
            ['kabupaten_id' => 54, 'nama' => "Ranah Ampek Hulu Tapan"],
            ['kabupaten_id' => 54, 'nama' => "Pancung Soal"],
            ['kabupaten_id' => 54, 'nama' => "Airpura"],
            ['kabupaten_id' => 54, 'nama' => "Linggo Sari Baganti"],
            ['kabupaten_id' => 54, 'nama' => "Ranah Pesisir"],
            ['kabupaten_id' => 54, 'nama' => "Lengayang"],
            ['kabupaten_id' => 54, 'nama' => "Sutera"],
            ['kabupaten_id' => 54, 'nama' => "Batang Kapas"],
            ['kabupaten_id' => 54, 'nama' => "Iv Jurai"],
            ['kabupaten_id' => 54, 'nama' => "Bayang"],
            ['kabupaten_id' => 54, 'nama' => "Iv  Nagari Bayang Utara"],
            ['kabupaten_id' => 54, 'nama' => "Koto Xi Tarusan"],
            ['kabupaten_id' => 55, 'nama' => "Pantai Cermin"],
            ['kabupaten_id' => 55, 'nama' => "Lembah Gumanti"],
            ['kabupaten_id' => 55, 'nama' => "Hiliran Gumanti"],
            ['kabupaten_id' => 55, 'nama' => "Payung Sekaki"],
            ['kabupaten_id' => 55, 'nama' => "Tigo Lurah"],
            ['kabupaten_id' => 55, 'nama' => "Lembang Jaya"],
            ['kabupaten_id' => 55, 'nama' => "Danau Kembar"],
            ['kabupaten_id' => 55, 'nama' => "Gunung Talang"],
            ['kabupaten_id' => 55, 'nama' => "Bukit Sundi"],
            ['kabupaten_id' => 55, 'nama' => "Ix Koto Sungai Lasi"],
            ['kabupaten_id' => 55, 'nama' => "Kubung"],
            ['kabupaten_id' => 55, 'nama' => "X Koto Diatas"],
            ['kabupaten_id' => 55, 'nama' => "X Koto Singkarak"],
            ['kabupaten_id' => 55, 'nama' => "Junjung Sirih"],
            ['kabupaten_id' => 56, 'nama' => "Kamang Baru"],
            ['kabupaten_id' => 56, 'nama' => "Tanjung Gadang"],
            ['kabupaten_id' => 56, 'nama' => "Sijunjung"],
            ['kabupaten_id' => 56, 'nama' => "Lubuk Tarok"],
            ['kabupaten_id' => 56, 'nama' => "Iv Nagari"],
            ['kabupaten_id' => 56, 'nama' => "Kupitan"],
            ['kabupaten_id' => 56, 'nama' => "Koto Tujuh"],
            ['kabupaten_id' => 56, 'nama' => "Sumpur Kudus"],
            ['kabupaten_id' => 57, 'nama' => "X Koto"],
            ['kabupaten_id' => 57, 'nama' => "Batipuh"],
            ['kabupaten_id' => 57, 'nama' => "Batipuh Selatan"],
            ['kabupaten_id' => 57, 'nama' => "Pariangan"],
            ['kabupaten_id' => 57, 'nama' => "Rambatan"],
            ['kabupaten_id' => 57, 'nama' => "Lima Kaum"],
            ['kabupaten_id' => 57, 'nama' => "Tanjung Emas"],
            ['kabupaten_id' => 57, 'nama' => "Padang Ganting"],
            ['kabupaten_id' => 57, 'nama' => "Lintau Buo"],
            ['kabupaten_id' => 57, 'nama' => "Lintau Buo Utara"],
            ['kabupaten_id' => 57, 'nama' => "Sungayang"],
            ['kabupaten_id' => 57, 'nama' => "Sungai Tarab"],
            ['kabupaten_id' => 57, 'nama' => "Salimpaung"],
            ['kabupaten_id' => 57, 'nama' => "Tanjung Baru"],
            ['kabupaten_id' => 58, 'nama' => "Batang Anai"],
            ['kabupaten_id' => 58, 'nama' => "Lubuk Alung"],
            ['kabupaten_id' => 58, 'nama' => "Sintuk Toboh Gadang"],
            ['kabupaten_id' => 58, 'nama' => "Ulakan Tapakis"],
            ['kabupaten_id' => 58, 'nama' => "Nan Sabaris"],
            ['kabupaten_id' => 58, 'nama' => "2 X 11 Enam Lingkung"],
            ['kabupaten_id' => 58, 'nama' => "Enam Lingkung"],
            ['kabupaten_id' => 58, 'nama' => "2 X 11 Kayu Tanam"],
            ['kabupaten_id' => 58, 'nama' => "Vii Koto Sungai Sariak"],
            ['kabupaten_id' => 58, 'nama' => "Patamuan"],
            ['kabupaten_id' => 58, 'nama' => "Padang Sago"],
            ['kabupaten_id' => 58, 'nama' => "V Koto Kp Dalam"],
            ['kabupaten_id' => 58, 'nama' => "V Koto Timur"],
            ['kabupaten_id' => 58, 'nama' => "Sungai Limau"],
            ['kabupaten_id' => 58, 'nama' => "Batang Gasan"],
            ['kabupaten_id' => 58, 'nama' => "Sungai Geringging"],
            ['kabupaten_id' => 58, 'nama' => "Iv Koto Aur Malintang"],
            ['kabupaten_id' => 59, 'nama' => "Tanjung Mutiara"],
            ['kabupaten_id' => 59, 'nama' => "Lubuk Basung"],
            ['kabupaten_id' => 59, 'nama' => "Ampek Nagari"],
            ['kabupaten_id' => 59, 'nama' => "Tanjung Raya"],
            ['kabupaten_id' => 59, 'nama' => "Matur"],
            ['kabupaten_id' => 59, 'nama' => "Iv Koto"],
            ['kabupaten_id' => 59, 'nama' => "Malalak"],
            ['kabupaten_id' => 59, 'nama' => "Banuhampu"],
            ['kabupaten_id' => 59, 'nama' => "Sungai Pua"],
            ['kabupaten_id' => 59, 'nama' => "Ampek Angkek"],
            ['kabupaten_id' => 59, 'nama' => "Canduang"],
            ['kabupaten_id' => 59, 'nama' => "Baso"],
            ['kabupaten_id' => 59, 'nama' => "Tilatang Kamang"],
            ['kabupaten_id' => 59, 'nama' => "Kamang Magek"],
            ['kabupaten_id' => 59, 'nama' => "Palembayan"],
            ['kabupaten_id' => 59, 'nama' => "Palupuh"],
            ['kabupaten_id' => 60, 'nama' => "Payakumbuh"],
            ['kabupaten_id' => 60, 'nama' => "Akabiluru"],
            ['kabupaten_id' => 60, 'nama' => "Luak"],
            ['kabupaten_id' => 60, 'nama' => "Lareh Sago Halaban"],
            ['kabupaten_id' => 60, 'nama' => "Situjuah Limo Nagari"],
            ['kabupaten_id' => 60, 'nama' => "Harau"],
            ['kabupaten_id' => 60, 'nama' => "Guguak"],
            ['kabupaten_id' => 60, 'nama' => "Mungka"],
            ['kabupaten_id' => 60, 'nama' => "Suliki"],
            ['kabupaten_id' => 60, 'nama' => "Bukik Barisan"],
            ['kabupaten_id' => 60, 'nama' => "Gunuang Omeh"],
            ['kabupaten_id' => 60, 'nama' => "Kapur Ix"],
            ['kabupaten_id' => 60, 'nama' => "Pangkalan Koto Baru"],
            ['kabupaten_id' => 61, 'nama' => "Bonjol"],
            ['kabupaten_id' => 61, 'nama' => "Tigo Nagari"],
            ['kabupaten_id' => 61, 'nama' => "Simpang Alahan Mati"],
            ['kabupaten_id' => 61, 'nama' => "Lubuk Sikaping"],
            ['kabupaten_id' => 61, 'nama' => "Dua Koto"],
            ['kabupaten_id' => 61, 'nama' => "Panti"],
            ['kabupaten_id' => 61, 'nama' => "Padang Gelugur"],
            ['kabupaten_id' => 61, 'nama' => "Rao"],
            ['kabupaten_id' => 61, 'nama' => "Mapat Tunggul"],
            ['kabupaten_id' => 61, 'nama' => "Mapat Tunggul Selatan"],
            ['kabupaten_id' => 61, 'nama' => "Rao Selatan"],
            ['kabupaten_id' => 61, 'nama' => "Rao Utara"],
            ['kabupaten_id' => 62, 'nama' => "Sangir"],
            ['kabupaten_id' => 62, 'nama' => "Sangir Jujuan"],
            ['kabupaten_id' => 62, 'nama' => "Sangir Balai Janggo"],
            ['kabupaten_id' => 62, 'nama' => "Sangir Batang Hari"],
            ['kabupaten_id' => 62, 'nama' => "Sungai Pagu"],
            ['kabupaten_id' => 62, 'nama' => "Pauah Duo"],
            ['kabupaten_id' => 62, 'nama' => "Koto Parik Gadang Diateh"],
            ['kabupaten_id' => 63, 'nama' => "Sungai Rumbai"],
            ['kabupaten_id' => 63, 'nama' => "Koto Besar"],
            ['kabupaten_id' => 63, 'nama' => "Asam Jujuhan"],
            ['kabupaten_id' => 63, 'nama' => "Koto Baru"],
            ['kabupaten_id' => 63, 'nama' => "Koto Salak"],
            ['kabupaten_id' => 63, 'nama' => "Tiumang"],
            ['kabupaten_id' => 63, 'nama' => "Padang Laweh"],
            ['kabupaten_id' => 63, 'nama' => "Sitiung"],
            ['kabupaten_id' => 63, 'nama' => "Timpeh"],
            ['kabupaten_id' => 63, 'nama' => "Pulau Punjung"],
            ['kabupaten_id' => 63, 'nama' => "Ix Koto"],
            ['kabupaten_id' => 64, 'nama' => "Kinali"],
            ['kabupaten_id' => 64, 'nama' => "Luhak Nan Duo"],
            ['kabupaten_id' => 64, 'nama' => "Pasaman"],
            ['kabupaten_id' => 64, 'nama' => "Gunung Tuleh "],
            ['kabupaten_id' => 64, 'nama' => "Ranah Bantahan"],
            ['kabupaten_id' => 64, 'nama' => "Koto Balingka"],
            ['kabupaten_id' => 64, 'nama' => "Sungai  Beremas"],
            ['kabupaten_id' => 64, 'nama' => "Lembah Malintang"],
            ['kabupaten_id' => 64, 'nama' => "Talamau"],
            ['kabupaten_id' => 64, 'nama' => "Sungai Aur"],
            ['kabupaten_id' => 64, 'nama' => "Sasak Ranah Pasisie"],
            ['kabupaten_id' => 65, 'nama' => "Padang Timur"],
            ['kabupaten_id' => 65, 'nama' => "Nanggalo"],
            ['kabupaten_id' => 65, 'nama' => "Koto Tangah"],
            ['kabupaten_id' => 66, 'nama' => "Silungkang"],
            ['kabupaten_id' => 66, 'nama' => "Lembah Segar"],
            ['kabupaten_id' => 66, 'nama' => "Barangin"],
            ['kabupaten_id' => 66, 'nama' => "Talawi"],
            ['kabupaten_id' => 67, 'nama' => "Payakumbuh Barat"],
            ['kabupaten_id' => 67, 'nama' => "Payakumbuh Timur"],
            ['kabupaten_id' => 67, 'nama' => "Payakumbuh Selatan"],
            ['kabupaten_id' => 67, 'nama' => "Payakumbuh Utara"],
            ['kabupaten_id' => 67, 'nama' => "Lamposi Tigo Nagori"],
            ['kabupaten_id' => 68, 'nama' => "Pariaman Selatan"],
            ['kabupaten_id' => 68, 'nama' => "Pariaman Tengah"],
            ['kabupaten_id' => 68, 'nama' => "Pariaman Timur"],
            ['kabupaten_id' => 68, 'nama' => "Pariaman Utara"],
            ['kabupaten_id' => 69, 'nama' => "Kuantan Hilir Seberang"],
            ['kabupaten_id' => 69, 'nama' => "Pangean"],
            ['kabupaten_id' => 69, 'nama' => "Inuman "],
            ['kabupaten_id' => 69, 'nama' => "Kuantan Mudik "],
            ['kabupaten_id' => 69, 'nama' => "Kuantan Hilir "],
            ['kabupaten_id' => 69, 'nama' => "Gunung Toar"],
            ['kabupaten_id' => 69, 'nama' => "Kuantan Tengah"],
            ['kabupaten_id' => 69, 'nama' => "Hulu Kuantan"],
            ['kabupaten_id' => 69, 'nama' => "Benai"],
            ['kabupaten_id' => 69, 'nama' => "Sentajo Raya"],
            ['kabupaten_id' => 69, 'nama' => "Cerenti "],
            ['kabupaten_id' => 70, 'nama' => "Kuala Cenaku"],
            ['kabupaten_id' => 70, 'nama' => "Rakit Kulim "],
            ['kabupaten_id' => 70, 'nama' => "Rengat"],
            ['kabupaten_id' => 70, 'nama' => "Rengat Barat"],
            ['kabupaten_id' => 70, 'nama' => "Kelayang"],
            ['kabupaten_id' => 70, 'nama' => "Pasir Penyu"],
            ['kabupaten_id' => 70, 'nama' => "Peranap"],
            ['kabupaten_id' => 70, 'nama' => "Batang Cenaku"],
            ['kabupaten_id' => 70, 'nama' => "Sungai Lala"],
            ['kabupaten_id' => 70, 'nama' => "Batang Peranap"],
            ['kabupaten_id' => 71, 'nama' => "Batang Tuaka "],
            ['kabupaten_id' => 71, 'nama' => "Tempuling "],
            ['kabupaten_id' => 71, 'nama' => "Kempas "],
            ['kabupaten_id' => 71, 'nama' => "Keritang "],
            ['kabupaten_id' => 71, 'nama' => "Reteh "],
            ['kabupaten_id' => 71, 'nama' => "Sungai Batang "],
            ['kabupaten_id' => 71, 'nama' => "Tembilahan Hulu "],
            ['kabupaten_id' => 71, 'nama' => "Enok "],
            ['kabupaten_id' => 71, 'nama' => "Tembilahan"],
            ['kabupaten_id' => 71, 'nama' => "Gaung "],
            ['kabupaten_id' => 71, 'nama' => "Kemuning "],
            ['kabupaten_id' => 72, 'nama' => "Teluk Meranti "],
            ['kabupaten_id' => 72, 'nama' => "Pangkalan Lesung"],
            ['kabupaten_id' => 72, 'nama' => "Pangkalan Kuras"],
            ['kabupaten_id' => 72, 'nama' => "Pelalawan"],
            ['kabupaten_id' => 72, 'nama' => "Kuala kampar"],
            ['kabupaten_id' => 73, 'nama' => "Bunga Raya "],
            ['kabupaten_id' => 73, 'nama' => "Tualang"],
            ['kabupaten_id' => 73, 'nama' => "Sungai Apit"],
            ['kabupaten_id' => 73, 'nama' => "Pusako "],
            ['kabupaten_id' => 73, 'nama' => "Sungai Mandau"],
            ['kabupaten_id' => 73, 'nama' => "Sabak Auh"],
            ['kabupaten_id' => 73, 'nama' => "Siak "],
            ['kabupaten_id' => 73, 'nama' => "Dayun "],
            ['kabupaten_id' => 73, 'nama' => "Mempura"],
            ['kabupaten_id' => 74, 'nama' => "Kampar"],
            ['kabupaten_id' => 74, 'nama' => "Bangkinang "],
            ['kabupaten_id' => 74, 'nama' => "Kampar Utara"],
            ['kabupaten_id' => 74, 'nama' => "Tapung"],
            ['kabupaten_id' => 74, 'nama' => "Kampa"],
            ['kabupaten_id' => 74, 'nama' => "Tambang"],
            ['kabupaten_id' => 74, 'nama' => "Salo"],
            ['kabupaten_id' => 74, 'nama' => "Rumbio Jaya"],
            ['kabupaten_id' => 74, 'nama' => "Kuok "],
            ['kabupaten_id' => 74, 'nama' => "Siak Hulu "],
            ['kabupaten_id' => 74, 'nama' => "Kampar Kiri "],
            ['kabupaten_id' => 75, 'nama' => "Rambah Samo"],
            ['kabupaten_id' => 75, 'nama' => "Bangun purba"],
            ['kabupaten_id' => 75, 'nama' => "Rambah Hilir"],
            ['kabupaten_id' => 75, 'nama' => "Ujung Batu"],
            ['kabupaten_id' => 75, 'nama' => "Rokan IV Koto"],
            ['kabupaten_id' => 75, 'nama' => "Rambah"],
            ['kabupaten_id' => 75, 'nama' => "Tambusai"],
            ['kabupaten_id' => 75, 'nama' => "Kepenuhan"],
            ['kabupaten_id' => 75, 'nama' => "Kunto Darussalam"],
            ['kabupaten_id' => 75, 'nama' => "Kepenuhan Hulu"],
            ['kabupaten_id' => 76, 'nama' => "Bantan "],
            ['kabupaten_id' => 76, 'nama' => "Siak Kecil "],
            ['kabupaten_id' => 76, 'nama' => "Bathin Solapan "],
            ['kabupaten_id' => 76, 'nama' => "Pinggir"],
            ['kabupaten_id' => 76, 'nama' => "Mandau "],
            ['kabupaten_id' => 76, 'nama' => "Bengkalis"],
            ['kabupaten_id' => 76, 'nama' => "Bukit Batu "],
            ['kabupaten_id' => 76, 'nama' => "Rupat"],
            ['kabupaten_id' => 76, 'nama' => "Bandar Laksamana "],
            ['kabupaten_id' => 77, 'nama' => "Bangko "],
            ['kabupaten_id' => 77, 'nama' => "Rimba Melintang "],
            ['kabupaten_id' => 77, 'nama' => "Sinaboi "],
            ['kabupaten_id' => 77, 'nama' => "Pekaitan "],
            ['kabupaten_id' => 77, 'nama' => "Batu Hampar "],
            ['kabupaten_id' => 77, 'nama' => "Bangko Pusako "],
            ['kabupaten_id' => 77, 'nama' => "Kubu "],
            ['kabupaten_id' => 77, 'nama' => "Pasir Limau Kapas"],
            ['kabupaten_id' => 77, 'nama' => "Kubu Babussalam"],
            ['kabupaten_id' => 78, 'nama' => "Rangsang Barat "],
            ['kabupaten_id' => 78, 'nama' => "Rangsang Pesisir"],
            ['kabupaten_id' => 78, 'nama' => "Tebing Tinggi Timur"],
            ['kabupaten_id' => 78, 'nama' => "Pulau Merbau"],
            ['kabupaten_id' => 78, 'nama' => "Tasik Putri Puyu"],
            ['kabupaten_id' => 78, 'nama' => "Tebing Tinggi  "],
            ['kabupaten_id' => 78, 'nama' => "Rangsang "],
            ['kabupaten_id' => 79, 'nama' => "Kulim "],
            ['kabupaten_id' => 79, 'nama' => "Rumbai "],
            ['kabupaten_id' => 79, 'nama' => "Tampan "],
            ['kabupaten_id' => 80, 'nama' => "Sungai Sembilan"],
            ['kabupaten_id' => 80, 'nama' => "Dumai selatan"],
            ['kabupaten_id' => 80, 'nama' => "Dumai Timur "],
            ['kabupaten_id' => 81, 'nama' => " Gunung Raya"],
            ['kabupaten_id' => 81, 'nama' => " Danau Kerinci"],
            ['kabupaten_id' => 81, 'nama' => " Sitinjau Laut"],
            ['kabupaten_id' => 81, 'nama' => " Air Hangat"],
            ['kabupaten_id' => 81, 'nama' => " Gunung Kerinci"],
            ['kabupaten_id' => 81, 'nama' => " Batang Merangin"],
            ['kabupaten_id' => 81, 'nama' => " Keliling Danau"],
            ['kabupaten_id' => 81, 'nama' => " Kayu Aro"],
            ['kabupaten_id' => 81, 'nama' => " Air Hangat Timur"],
            ['kabupaten_id' => 81, 'nama' => " Gunung Tujuh"],
            ['kabupaten_id' => 81, 'nama' => " Siulak"],
            ['kabupaten_id' => 81, 'nama' => " Depati Tujuh"],
            ['kabupaten_id' => 81, 'nama' => " Siulak Mukait"],
            ['kabupaten_id' => 81, 'nama' => " Kayu Aro Barat"],
            ['kabupaten_id' => 81, 'nama' => " Bukit Kerman"],
            ['kabupaten_id' => 81, 'nama' => " Air Hangat Barat"],
            ['kabupaten_id' => 81, 'nama' => "Danau Kerinci Barat"],
            ['kabupaten_id' => 81, 'nama' => "Tanah Coguk"],
            ['kabupaten_id' => 82, 'nama' => "Bangko"],
            ['kabupaten_id' => 82, 'nama' => "Tabir"],
            ['kabupaten_id' => 82, 'nama' => "Jangkat"],
            ['kabupaten_id' => 82, 'nama' => "Sungai Manau"],
            ['kabupaten_id' => 82, 'nama' => "Muara Siau"],
            ['kabupaten_id' => 82, 'nama' => "Pamenang"],
            ['kabupaten_id' => 82, 'nama' => "Tabir Ulu"],
            ['kabupaten_id' => 82, 'nama' => "Tabir Selatan"],
            ['kabupaten_id' => 82, 'nama' => "Lembah Masurai"],
            ['kabupaten_id' => 82, 'nama' => "Bangko Barat"],
            ['kabupaten_id' => 82, 'nama' => "Nalo Tantan"],
            ['kabupaten_id' => 82, 'nama' => "Batang Masumai"],
            ['kabupaten_id' => 82, 'nama' => "Pamenang Barat"],
            ['kabupaten_id' => 82, 'nama' => "Tabir Ilir"],
            ['kabupaten_id' => 82, 'nama' => "Tabir Timur"],
            ['kabupaten_id' => 82, 'nama' => "Renah Pembarap"],
            ['kabupaten_id' => 82, 'nama' => "Pangkalan Jambu"],
            ['kabupaten_id' => 82, 'nama' => "Renah Pamenang"],
            ['kabupaten_id' => 82, 'nama' => "Pemenang Selatan"],
            ['kabupaten_id' => 82, 'nama' => "Margo Tabir"],
            ['kabupaten_id' => 82, 'nama' => "Tabir Lintas"],
            ['kabupaten_id' => 82, 'nama' => "Tabir Barat"],
            ['kabupaten_id' => 82, 'nama' => "Tiang Pumpung"],
            ['kabupaten_id' => 82, 'nama' => "Jangkat Timur"],
            ['kabupaten_id' => 83, 'nama' => "Sarolangun"],
            ['kabupaten_id' => 83, 'nama' => "Batang Asai"],
            ['kabupaten_id' => 83, 'nama' => "Limun "],
            ['kabupaten_id' => 83, 'nama' => "Pauh"],
            ['kabupaten_id' => 83, 'nama' => "Pelawan "],
            ['kabupaten_id' => 83, 'nama' => "Singkut"],
            ['kabupaten_id' => 83, 'nama' => "Mandiangin"],
            ['kabupaten_id' => 83, 'nama' => "Air Hitam"],
            ['kabupaten_id' => 83, 'nama' => "Bathin VIII"],
            ['kabupaten_id' => 83, 'nama' => "Cermin Nan Gedang"],
            ['kabupaten_id' => 83, 'nama' => "Mandiangin Timur"],
            ['kabupaten_id' => 84, 'nama' => "Mersam "],
            ['kabupaten_id' => 84, 'nama' => "Muara Tembesi"],
            ['kabupaten_id' => 84, 'nama' => "Muara Bulian"],
            ['kabupaten_id' => 84, 'nama' => "Batin XXIV"],
            ['kabupaten_id' => 84, 'nama' => "Pemayung"],
            ['kabupaten_id' => 84, 'nama' => "Maro Sebo Ilir"],
            ['kabupaten_id' => 84, 'nama' => "Bajubang/Bajubang"],
            ['kabupaten_id' => 84, 'nama' => "Maro Sebo Ulu "],
            ['kabupaten_id' => 85, 'nama' => "Jambi Luar Kota/Pijoan"],
            ['kabupaten_id' => 85, 'nama' => "Sekernan/Sengeti"],
            ['kabupaten_id' => 85, 'nama' => "Kumpeh Ilir/Tanjung"],
            ['kabupaten_id' => 85, 'nama' => "Maro Sebo/Jambi Kecil"],
            ['kabupaten_id' => 85, 'nama' => "Mestong/Sebapo"],
            ['kabupaten_id' => 85, 'nama' => "Kumpeh Ulu /Pudak"],
            ['kabupaten_id' => 85, 'nama' => "Sungai Bahar/Sungai Bahar"],
            ['kabupaten_id' => 85, 'nama' => "Sungai Gelam/Sungai Gelam"],
            ['kabupaten_id' => 85, 'nama' => "Sungai Bahar Utara/Talang Bukit"],
            ['kabupaten_id' => 85, 'nama' => "Bahar Selatan/Tanjung Mulia"],
            ['kabupaten_id' => 85, 'nama' => "Taman Rajo/Kemungking Dalam"],
            ['kabupaten_id' => 86, 'nama' => "Muara Sabak /Muara Sabak"],
            ['kabupaten_id' => 86, 'nama' => "Nipah Panjang/Nipah Panjang"],
            ['kabupaten_id' => 86, 'nama' => "Mendahara/Mendahara Ilir"],
            ['kabupaten_id' => 86, 'nama' => "Rantau Rasau/Bandar Jaya"],
            ['kabupaten_id' => 86, 'nama' => "Sadu/Sungai Lokan"],
            ['kabupaten_id' => 86, 'nama' => "Dendang/Rantau Indah"],
            ['kabupaten_id' => 86, 'nama' => "Muara Sabak Barat/Nibang Putih"],
            ['kabupaten_id' => 86, 'nama' => "Mendahara Ulu/Simpang Kiri"],
            ['kabupaten_id' => 86, 'nama' => "Kuala JambiKampung Laut"],
            ['kabupaten_id' => 86, 'nama' => "Geragai/Pandan Jaya"],
            ['kabupaten_id' => 86, 'nama' => "Berbak/Desa Simpang"],
            ['kabupaten_id' => 87, 'nama' => "Tungkal Ulu"],
            ['kabupaten_id' => 87, 'nama' => "Tungkal Ilir"],
            ['kabupaten_id' => 87, 'nama' => "Pengabuan"],
            ['kabupaten_id' => 87, 'nama' => "Betara"],
            ['kabupaten_id' => 87, 'nama' => "Merlung"],
            ['kabupaten_id' => 87, 'nama' => "Tebing Tinggi"],
            ['kabupaten_id' => 87, 'nama' => "Batang Asam"],
            ['kabupaten_id' => 87, 'nama' => "Renah Mendaluh"],
            ['kabupaten_id' => 87, 'nama' => "Muara Papalik"],
            ['kabupaten_id' => 87, 'nama' => "Seberang Kota"],
            ['kabupaten_id' => 87, 'nama' => "Bram Itam"],
            ['kabupaten_id' => 87, 'nama' => "Kuala Betara"],
            ['kabupaten_id' => 87, 'nama' => "Senyerang"],
            ['kabupaten_id' => 88, 'nama' => "VII Koto"],
            ['kabupaten_id' => 88, 'nama' => "VII Koto Ilir"],
            ['kabupaten_id' => 88, 'nama' => "Muara Tabir"],
            ['kabupaten_id' => 88, 'nama' => "Rimbo Bujang"],
            ['kabupaten_id' => 88, 'nama' => "Rimbo Ilir"],
            ['kabupaten_id' => 88, 'nama' => "Rimbo Ulu"],
            ['kabupaten_id' => 88, 'nama' => "Serai Serumpun"],
            ['kabupaten_id' => 88, 'nama' => "Sumay"],
            ['kabupaten_id' => 88, 'nama' => "Tebo Ilir"],
            ['kabupaten_id' => 88, 'nama' => "Tebo Tengah"],
            ['kabupaten_id' => 88, 'nama' => "Tebo Ulu"],
            ['kabupaten_id' => 88, 'nama' => "Tengah Ilir"],
            ['kabupaten_id' => 89, 'nama' => "Bathin II Pelayang"],
            ['kabupaten_id' => 89, 'nama' => "Pasar Muara Bungo"],
            ['kabupaten_id' => 89, 'nama' => "Rantau Pandan"],
            ['kabupaten_id' => 89, 'nama' => "Tanah Tumbuh"],
            ['kabupaten_id' => 89, 'nama' => "Jujuhan"],
            ['kabupaten_id' => 89, 'nama' => "Tanah Sepenggal"],
            ['kabupaten_id' => 89, 'nama' => "Pelepat"],
            ['kabupaten_id' => 89, 'nama' => "Muko-Muko Batin VII"],
            ['kabupaten_id' => 89, 'nama' => "Limbur Lbk Mengkuang"],
            ['kabupaten_id' => 89, 'nama' => "Pelepat Ilir"],
            ['kabupaten_id' => 89, 'nama' => "Bathin II Babeko"],
            ['kabupaten_id' => 89, 'nama' => "Bathin III"],
            ['kabupaten_id' => 89, 'nama' => "Bungo Dani"],
            ['kabupaten_id' => 89, 'nama' => "Rimbo Tengah"],
            ['kabupaten_id' => 89, 'nama' => "Bathin III Ulu"],
            ['kabupaten_id' => 89, 'nama' => "Tanah Sepenggal Lintas"],
            ['kabupaten_id' => 89, 'nama' => "Jujuhan Ilir"],
            ['kabupaten_id' => 90, 'nama' => "Sungai Penuh"],
            ['kabupaten_id' => 90, 'nama' => "Hamparan Rawan"],
            ['kabupaten_id' => 90, 'nama' => "Pesisir Bukit"],
            ['kabupaten_id' => 90, 'nama' => "Kumun Debai"],
            ['kabupaten_id' => 90, 'nama' => "Tanah Kampung"],
            ['kabupaten_id' => 90, 'nama' => "Pondok Tinggi"],
            ['kabupaten_id' => 90, 'nama' => "Koto Baru"],
            ['kabupaten_id' => 90, 'nama' => "Sungaibungkal"],
            ['kabupaten_id' => 91, 'nama' => "Kota Baru"],
            ['kabupaten_id' => 91, 'nama' => "Telanaipura"],
            ['kabupaten_id' => 91, 'nama' => "Danau Teluk"],
            ['kabupaten_id' => 91, 'nama' => "Pelayangan"],
            ['kabupaten_id' => 91, 'nama' => "Jambi Timur"],
            ['kabupaten_id' => 91, 'nama' => "Alam Barajo"],
            ['kabupaten_id' => 91, 'nama' => "Palmerah"],
            ['kabupaten_id' => 92, 'nama' => "Seginim"],
            ['kabupaten_id' => 92, 'nama' => "Pino"],
            ['kabupaten_id' => 92, 'nama' => "Manna"],
            ['kabupaten_id' => 92, 'nama' => "Kota Manna"],
            ['kabupaten_id' => 92, 'nama' => "Pino Raya"],
            ['kabupaten_id' => 92, 'nama' => "Kedurang Ilir "],
            ['kabupaten_id' => 92, 'nama' => "Air Nipis"],
            ['kabupaten_id' => 92, 'nama' => "Ulu Manna"],
            ['kabupaten_id' => 92, 'nama' => "Bunga Mas"],
            ['kabupaten_id' => 92, 'nama' => "Pasar Manna"],
            ['kabupaten_id' => 92, 'nama' => "Seginim"],
            ['kabupaten_id' => 92, 'nama' => "Air Nipis"],
            ['kabupaten_id' => 92, 'nama' => "Kedurang"],
            ['kabupaten_id' => 93, 'nama' => "Bermani Ulu"],
            ['kabupaten_id' => 93, 'nama' => "Selupu Rejang"],
            ['kabupaten_id' => 93, 'nama' => "Bermani Ulu Raya"],
            ['kabupaten_id' => 94, 'nama' => "Marga Sakti Sebelat"],
            ['kabupaten_id' => 94, 'nama' => "Putri Hijau"],
            ['kabupaten_id' => 94, 'nama' => "Enggano"],
            ['kabupaten_id' => 94, 'nama' => "Ulok Kupai"],
            ['kabupaten_id' => 94, 'nama' => "Pinang Raya"],
            ['kabupaten_id' => 94, 'nama' => "Padang Jaya"],
            ['kabupaten_id' => 94, 'nama' => "Batik Nau"],
            ['kabupaten_id' => 94, 'nama' => "Tanjung Agung Palik"],
            ['kabupaten_id' => 94, 'nama' => "Hulu Palik"],
            ['kabupaten_id' => 94, 'nama' => "Air Padang"],
            ['kabupaten_id' => 94, 'nama' => "Tanjung Agung Palik"],
            ['kabupaten_id' => 94, 'nama' => "Air Napal"],
            ['kabupaten_id' => 95, 'nama' => "Tanjung Kemuning"],
            ['kabupaten_id' => 95, 'nama' => "Kaur Utara"],
            ['kabupaten_id' => 95, 'nama' => "Luas"],
            ['kabupaten_id' => 95, 'nama' => "Kelam Tengah"],
            ['kabupaten_id' => 95, 'nama' => "Lungkang Kule"],
            ['kabupaten_id' => 95, 'nama' => "Padang Guci Hilir"],
            ['kabupaten_id' => 95, 'nama' => "Padang Guci Hulu"],
            ['kabupaten_id' => 95, 'nama' => "Kinal"],
            ['kabupaten_id' => 95, 'nama' => "Kaur Tengah"],
            ['kabupaten_id' => 95, 'nama' => "Nasal"],
            ['kabupaten_id' => 95, 'nama' => "Semidang Gumay"],
            ['kabupaten_id' => 95, 'nama' => "Kaur Selatan"],
            ['kabupaten_id' => 95, 'nama' => "Tetap"],
            ['kabupaten_id' => 95, 'nama' => "Maje"],
            ['kabupaten_id' => 96, 'nama' => "Lubuk Sandi"],
            ['kabupaten_id' => 96, 'nama' => "Seluma Timur"],
            ['kabupaten_id' => 96, 'nama' => "Talo Kecil"],
            ['kabupaten_id' => 96, 'nama' => "Ilir Talo"],
            ['kabupaten_id' => 96, 'nama' => "Talo"],
            ['kabupaten_id' => 96, 'nama' => "Semidang Alas"],
            ['kabupaten_id' => 96, 'nama' => "Semidang Alas Maras"],
            ['kabupaten_id' => 96, 'nama' => "Ulu Talo"],
            ['kabupaten_id' => 96, 'nama' => "Sukaraja"],
            ['kabupaten_id' => 96, 'nama' => "Air Periukan"],
            ['kabupaten_id' => 96, 'nama' => "Seluma Selatan"],
            ['kabupaten_id' => 97, 'nama' => "Ipuh"],
            ['kabupaten_id' => 97, 'nama' => "Malin Deman"],
            ['kabupaten_id' => 97, 'nama' => "Lubuk Pinang"],
            ['kabupaten_id' => 98, 'nama' => "Lebong Utara"],
            ['kabupaten_id' => 98, 'nama' => "Tubei"],
            ['kabupaten_id' => 99, 'nama' => "Sebrang Musi"],
            ['kabupaten_id' => 99, 'nama' => "Tebat Karai"],
            ['kabupaten_id' => 99, 'nama' => "Seberang Musi"],
            ['kabupaten_id' => 99, 'nama' => "Muara Kemumu"],
            ['kabupaten_id' => 100, 'nama' => "Taba Penanjung"],
            ['kabupaten_id' => 100, 'nama' => "Talang Empat"],
            ['kabupaten_id' => 100, 'nama' => "Talang Empat"],
            ['kabupaten_id' => 100, 'nama' => "Pondok Kelapa"],
            ['kabupaten_id' => 101, 'nama' => "Ratu Agung"],
            ['kabupaten_id' => 101, 'nama' => "Sungai Serut"],
            ['kabupaten_id' => 102, 'nama' => "Lengkiti"],
            ['kabupaten_id' => 102, 'nama' => "Sosoh Buay Rayap"],
            ['kabupaten_id' => 102, 'nama' => "Pengandonan"],
            ['kabupaten_id' => 102, 'nama' => "Muara Jaya"],
            ['kabupaten_id' => 102, 'nama' => "Ulu Ogan"],
            ['kabupaten_id' => 102, 'nama' => "Semidang Aji"],
            ['kabupaten_id' => 102, 'nama' => "Sinar Peninjauan"],
            ['kabupaten_id' => 102, 'nama' => "Lubuk Raja"],
            ['kabupaten_id' => 102, 'nama' => "Baturaja Timur"],
            ['kabupaten_id' => 102, 'nama' => "Lubuk Batang"],
            ['kabupaten_id' => 102, 'nama' => "Baturaja Barat"],
            ['kabupaten_id' => 102, 'nama' => "Peninjauan"],
            ['kabupaten_id' => 102, 'nama' => "Kedaton Peninjauan R"],
            ['kabupaten_id' => 103, 'nama' => "Kayu Agung"],
            ['kabupaten_id' => 103, 'nama' => "Mesuji"],
            ['kabupaten_id' => 103, 'nama' => "Pampangan"],
            ['kabupaten_id' => 103, 'nama' => "Pedamaran"],
            ['kabupaten_id' => 103, 'nama' => "Sirah Pulau Padang"],
            ['kabupaten_id' => 103, 'nama' => "Tanjung Lubuk"],
            ['kabupaten_id' => 103, 'nama' => "Tulung Selapan"],
            ['kabupaten_id' => 103, 'nama' => "Air Sugihan"],
            ['kabupaten_id' => 103, 'nama' => "Cengal"],
            ['kabupaten_id' => 103, 'nama' => "Jejawi"],
            ['kabupaten_id' => 103, 'nama' => "Lempuing Jaya"],
            ['kabupaten_id' => 103, 'nama' => "Mesuji Raya"],
            ['kabupaten_id' => 103, 'nama' => "Pangkalan Lampam"],
            ['kabupaten_id' => 103, 'nama' => "Sungai Menang"],
            ['kabupaten_id' => 103, 'nama' => "Teluk Gelam"],
            ['kabupaten_id' => 103, 'nama' => "Lempuing"],
            ['kabupaten_id' => 103, 'nama' => "Mesuji Makmur"],
            ['kabupaten_id' => 103, 'nama' => "Pedamaran Timur"],
            ['kabupaten_id' => 104, 'nama' => "Tanjung Agung"],
            ['kabupaten_id' => 104, 'nama' => "Muara Enim"],
            ['kabupaten_id' => 104, 'nama' => "Gunung Megang"],
            ['kabupaten_id' => 104, 'nama' => "Semende Darat Laut"],
            ['kabupaten_id' => 104, 'nama' => "Semende Darat Tengah"],
            ['kabupaten_id' => 104, 'nama' => "Semende Darat Ulu"],
            ['kabupaten_id' => 104, 'nama' => "Ujan Mas"],
            ['kabupaten_id' => 104, 'nama' => "Sungai Rotan"],
            ['kabupaten_id' => 104, 'nama' => "Benakat"],
            ['kabupaten_id' => 104, 'nama' => "Muara Belida"],
            ['kabupaten_id' => 104, 'nama' => "Belimbing"],
            ['kabupaten_id' => 104, 'nama' => "Empat Petulai Dangku"],
            ['kabupaten_id' => 104, 'nama' => "Panang Enim"],
            ['kabupaten_id' => 105, 'nama' => "Gumai Talang"],
            ['kabupaten_id' => 105, 'nama' => "Lahat"],
            ['kabupaten_id' => 105, 'nama' => "Lahat Selatan"],
            ['kabupaten_id' => 105, 'nama' => "TANJUNG SAKTI PUMI"],
            ['kabupaten_id' => 105, 'nama' => "TANJUNG SAKTI PUMU"],
            ['kabupaten_id' => 105, 'nama' => "KOTA AGUNG"],
            ['kabupaten_id' => 105, 'nama' => "MULAK ULU"],
            ['kabupaten_id' => 105, 'nama' => "TANJUNG TEBAT"],
            ['kabupaten_id' => 105, 'nama' => "MULAK SEBINGKAI"],
            ['kabupaten_id' => 105, 'nama' => "PULAU PINANG"],
            ['kabupaten_id' => 105, 'nama' => "PAGAR GUNUNG"],
            ['kabupaten_id' => 105, 'nama' => "GUMAY ULU"],
            ['kabupaten_id' => 105, 'nama' => "JARAI"],
            ['kabupaten_id' => 105, 'nama' => "PAJAR BULAN"],
            ['kabupaten_id' => 105, 'nama' => "MUARA PAYANG"],
            ['kabupaten_id' => 105, 'nama' => "SUKAMERINDU"],
            ['kabupaten_id' => 105, 'nama' => "KIKIM BARAT"],
            ['kabupaten_id' => 105, 'nama' => "KIKIM TIMUR"],
            ['kabupaten_id' => 105, 'nama' => "KIKIM SELATAN"],
            ['kabupaten_id' => 105, 'nama' => "KIKIM TENGAH"],
            ['kabupaten_id' => 105, 'nama' => "PSEKSU"],
            ['kabupaten_id' => 105, 'nama' => "MERAPI BARAT"],
            ['kabupaten_id' => 105, 'nama' => "MERAPI TIMUR"],
            ['kabupaten_id' => 105, 'nama' => "MERAPI SELATAN"],
            ['kabupaten_id' => 106, 'nama' => "Muara Lakitan"],
            ['kabupaten_id' => 106, 'nama' => "Muara Kelingi"],
            ['kabupaten_id' => 106, 'nama' => "STL Ulu Terawas"],
            ['kabupaten_id' => 106, 'nama' => "Bulang Tengah Suku Ulu"],
            ['kabupaten_id' => 106, 'nama' => "Tuah Negeri"],
            ['kabupaten_id' => 107, 'nama' => "Sanga Desa"],
            ['kabupaten_id' => 107, 'nama' => "Lais"],
            ['kabupaten_id' => 107, 'nama' => "Sekayu"],
            ['kabupaten_id' => 107, 'nama' => "Babat toman"],
            ['kabupaten_id' => 107, 'nama' => "Bayung lencir"],
            ['kabupaten_id' => 107, 'nama' => "Lalan"],
            ['kabupaten_id' => 107, 'nama' => "Sungai Lilin"],
            ['kabupaten_id' => 107, 'nama' => "Sungai Keruh"],
            ['kabupaten_id' => 107, 'nama' => "Batanghari leko"],
            ['kabupaten_id' => 107, 'nama' => "lawang wetan"],
            ['kabupaten_id' => 107, 'nama' => "babat supat"],
            ['kabupaten_id' => 107, 'nama' => "jirak jaya"],
            ['kabupaten_id' => 108, 'nama' => "Rambutan"],
            ['kabupaten_id' => 108, 'nama' => "Sembawa"],
            ['kabupaten_id' => 108, 'nama' => "Banyuasin III"],
            ['kabupaten_id' => 109, 'nama' => "Muara Dua"],
            ['kabupaten_id' => 109, 'nama' => "Pulau Beringin"],
            ['kabupaten_id' => 109, 'nama' => "Banding Agung"],
            ['kabupaten_id' => 109, 'nama' => "Simpang"],
            ['kabupaten_id' => 109, 'nama' => "Buay Sandang Aji"],
            ['kabupaten_id' => 109, 'nama' => "Buay Runjung"],
            ['kabupaten_id' => 109, 'nama' => "Mekakau Ilir"],
            ['kabupaten_id' => 109, 'nama' => "Buay Pemaca"],
            ['kabupaten_id' => 109, 'nama' => "Kisam Tinggi"],
            ['kabupaten_id' => 109, 'nama' => "Buay Pematang Ribu Ranau Tengah"],
            ['kabupaten_id' => 109, 'nama' => "Warkuk Ranau Selatan"],
            ['kabupaten_id' => 109, 'nama' => "Runjung Agung"],
            ['kabupaten_id' => 109, 'nama' => "Sungai Are"],
            ['kabupaten_id' => 109, 'nama' => "Sindang Danau"],
            ['kabupaten_id' => 109, 'nama' => "Buana Pemaca"],
            ['kabupaten_id' => 109, 'nama' => "Tiga Dihaji"],
            ['kabupaten_id' => 109, 'nama' => "Buay Rawan"],
            ['kabupaten_id' => 110, 'nama' => "Madang Suku I"],
            ['kabupaten_id' => 110, 'nama' => "Jayapura"],
            ['kabupaten_id' => 110, 'nama' => "Martapura"],
            ['kabupaten_id' => 110, 'nama' => "Cempaka"],
            ['kabupaten_id' => 110, 'nama' => "Belitang II"],
            ['kabupaten_id' => 110, 'nama' => "Madang Suku II"],
            ['kabupaten_id' => 110, 'nama' => "Madang Suku III"],
            ['kabupaten_id' => 110, 'nama' => "Buay Pemuka Peliung"],
            ['kabupaten_id' => 110, 'nama' => "Semendawai Barat"],
            ['kabupaten_id' => 110, 'nama' => "Buay Pemuka bangsa Raja"],
            ['kabupaten_id' => 110, 'nama' => "Bunga Mayang"],
            ['kabupaten_id' => 111, 'nama' => "Lubuk Keliat"],
            ['kabupaten_id' => 111, 'nama' => "Muara Kuang"],
            ['kabupaten_id' => 111, 'nama' => "Pemulutan"],
            ['kabupaten_id' => 111, 'nama' => "Rantau Panjang"],
            ['kabupaten_id' => 111, 'nama' => "Indralaya"],
            ['kabupaten_id' => 111, 'nama' => "Indralaya Utara"],
            ['kabupaten_id' => 111, 'nama' => "Indralaya Selatan"],
            ['kabupaten_id' => 111, 'nama' => "Tanjung Raja"],
            ['kabupaten_id' => 111, 'nama' => "Pemulatan Selatan"],
            ['kabupaten_id' => 111, 'nama' => "Pemulatan Barat"],
            ['kabupaten_id' => 111, 'nama' => "Sungai Pinang"],
            ['kabupaten_id' => 111, 'nama' => "Rantau Alai"],
            ['kabupaten_id' => 111, 'nama' => "Tanjung Batu"],
            ['kabupaten_id' => 111, 'nama' => "Kandis"],
            ['kabupaten_id' => 112, 'nama' => "Tebing Tinggi"],
            ['kabupaten_id' => 112, 'nama' => "Saling"],
            ['kabupaten_id' => 113, 'nama' => "Tanah Abang"],
            ['kabupaten_id' => 113, 'nama' => "Talang Ubi"],
            ['kabupaten_id' => 113, 'nama' => "Abab"],
            ['kabupaten_id' => 114, 'nama' => "Rupit "],
            ['kabupaten_id' => 114, 'nama' => "Rawas Ulu"],
            ['kabupaten_id' => 114, 'nama' => "Rawas Ilir"],
            ['kabupaten_id' => 114, 'nama' => "Karang Dapo"],
            ['kabupaten_id' => 114, 'nama' => "Karang Jaya"],
            ['kabupaten_id' => 114, 'nama' => "Ulu Rawas"],
            ['kabupaten_id' => 115, 'nama' => "Prabumulih Barat"],
            ['kabupaten_id' => 116, 'nama' => "Lubuk Linggau Selatan I"],
            ['kabupaten_id' => 116, 'nama' => "Lubuk Linggau Selatan II"],
            ['kabupaten_id' => 116, 'nama' => "Lubuk Linggau Utara I"],
            ['kabupaten_id' => 116, 'nama' => "Lubuk Linggau Barat I"],
            ['kabupaten_id' => 116, 'nama' => "Lubuk Linggau Barat II"],
            ['kabupaten_id' => 117, 'nama' => "Belinyu"],
            ['kabupaten_id' => 117, 'nama' => "Merawang"],
            ['kabupaten_id' => 117, 'nama' => "Mendo Barat"],
            ['kabupaten_id' => 117, 'nama' => "Riau Silip "],
            ['kabupaten_id' => 117, 'nama' => "Puding Besar"],
            ['kabupaten_id' => 117, 'nama' => "Bakam"],
        ];
        

        DB::table('kecamatan')->insert($kecamatan);
    }
}
